### ISSUE TITLE
why lastconnected value of device not be updated, when use device-mqtt-go send data to edgex-go? 

### ISSUE THREAD

**Issue by saintyfra** [edgexfoundry/device-mqtt-go#100]

**Comment by weichou1229** [comment]
@saintyfra Please provide the steps to reproduce your issue. 
You can refer to the edgex doc https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide#Contributor'sGuide-HowtoReportanIssue .

**Comment by cloudxxx8** [comment]
@saintyfra thanks for reporting this issue.
However, this is an universal issue, not limited to device-mqtt
I've opened the one in device-sdk, and we should fix this issue there
https://github.com/edgexfoundry/device-sdk-go/issues/371
