### ISSUE TITLE
Error - Handle read commands failed: can not fetch command reading: method=get cmd=ping"

### ISSUE THREAD

**Issue by Salvocll** [edgexfoundry/device-mqtt-go#114]
Hi, 

I followed the official guide and regarding the commissioning of the mqtt device service is ok.
I found it a bit difficult to start the javascript script with the container, so I decided to "translate" it into python.

I can run the command that changes the value of "message" and it's ok, but when I execute any commands "get" I obtain ever some error like this in case of ping get:

```
edgex-device-mqtt  | level=INFO ts=2019-10-24T16:58:07.998849995Z app=edgex-device-mqtt source=responselistener.go:63 msg="[Response listener] Command response received: topic=CommandTopic uuid=5db1d81fb8dd790001196ed8 msg={\"cmd\":\"ping\",\"method\":\"get\",\"uuid\":\"5db1d81fb8dd790001196ed8\"}"
edgex-device-mqtt  | level=INFO ts=2019-10-24T16:58:08.006393298Z app=edgex-device-mqtt source=driver.go:163 msg="Parse command response: {\"cmd\":\"ping\",\"method\":\"get\",\"uuid\":\"5db1d81fb8dd790001196ed8\"}"
edgex-device-mqtt  | level=INFO ts=2019-10-24T16:58:08.014736157Z app=edgex-device-mqtt source=driver.go:122 msg="Handle read commands failed: can not fetch command reading: method=get cmd=ping"
```

My code is this:

```
def handler_command_topic(paylaod):
    global message
    data = loads(paylaod)
    if data['method'] == 'set':
        message = data.message
        print(f"new message: {message}")
    else:
        if data['cmd'] == 'ping':
            data['ping'] = 'pong'
        elif data['cmd']== 'message':
            data['message'] = message
        elif data['cmd'] == 'randnum':
            data['randnum'] = 12.123
    print(data)
    client.publish("ResponseTopic", payload = dumps(data))


def on_message(client, userdata, msg):
    print('Topic: ' + msg.topic + '\nMessage: ' + str(msg.payload))
    if msg.topic == 'CommandTopic':
        handler_command_topic(msg.payload)


deviceName = "MQ_DEVICE"
broker_address="localhost"
client = mqtt.Client("DeviceSimulator") #create new instance
client.on_connect = on_connect
client.on_message = on_message
client.connect(broker_address) #connect to broker
client.subscribe('CommandTopic')
client.loop_forever()
```

Thanks in advance..

**Comment by anonyle47** [comment]
Hello @Salvocll, 

In fact, I have the same issue.
Could you please send me all the steps that you have used because I can't use this command to send message using this command line :  **curl http://your-edgex-server-ip:48082/api/v1/device/ddb2f5cf-eec2-4345-86ee-f0d87e6f77ff/command/0c257a37-2f72-4d23-b2b1-2c08e895060a -H "Content-Type:application/json" -X PUT  -d '{"message":"Hello!"}'**

![GET_PUT_not_work](https://user-images.githubusercontent.com/56597615/67557546-97859a00-f715-11e9-808e-b1eab73e3326.png)

Thank you

**Comment by weichou1229** [comment]
@Salvocll 
Did you mean mqtt-scripts is work but python not work?

**Comment by Salvocll** [comment]
@weichou1229 

I could not test the correct functioning of mqtt-scripts because I was not able to correctly communicate the container that runs the script with the broker mqtt consequently I translated mqtt-scripts from javascript in python and regarding the PUT request of the message and sending the data to the corresponding topic everything works correctly but when it executes the GET requests for the other parameters through the URLs of the device service these give me the error I reported .. you could also test yourself and if possible also the possible error that I have shop assistant? I would be grateful..

**Comment by weichou1229** [comment]
@Salvocll Could you verify the MQTT broker and mqtt-scripts are work correctly?
Step1: Deploy the broker and mqtt-scripts
```
docker run -d --rm --name broker -p 1883:1883 eclipse-mosquitto

docker run -d --restart=always --name=mqtt-scripts \
  -v /path/to/your/scripts:/scripts  \
  dersimn/mqtt-scripts --url mqtt://172.17.0.1 --dir /scripts
```

Step2: Use mosquitto client tool to check the mqtt message 
```
# Subscribe all topic from broker
./mosquitto_sub -v -t '#'

# Send command to broker
./mosquitto_pub -t 'CommandTopic' -m '{"name":"MQTT test device","method":"get","cmd":"ping"}'
```

The test result will like:
![image](https://user-images.githubusercontent.com/11187505/68731840-5bef3900-060c-11ea-974a-41887a9c0404.png)

The async value keeps logging to the console. The mqtt-scripts receive the request and send the response.

**Comment by weichou1229** [comment]
@Salvocll Do you still got the error? Is it fine to close this issue?

**Comment by Salvocll** [comment]
@weichou1229 Hi, sorry but I didn't have time to test it..

**Comment by weichou1229** [comment]
@Salvocll 
Since the fuji version released, you can test with the new version. 
And the document also updated according to your feedback.
https://github.com/edgexfoundry/edgex-docs/blob/fuji/examples/Ch-ExamplesAddingMQTTDevice.rst

**Comment by weichou1229** [comment]
Document made. Close inactivity issue
