### ISSUE TITLE
Reading data type conversion problem: float64 to int64、int32....

### ISSUE THREAD

**Issue by AhaEdgar** [edgexfoundry/device-mqtt-go#12]
==================================================================
device-mqtt-go/internal/dirver/incominglistener.go Line 54

```
func onIncomingDataReceived(client mqtt.Client, message mqtt.Message) {
	var response map[string]interface{}
	json.Unmarshal(message.Payload(), &response)
        .......
```

device-mqtt-go/internal/dirver/driver.go Line 296 
```
func newResult(deviceObject models.DeviceObject, ro models.ResourceOperation, reading interface{}) (*sdkModel.CommandValue, error) {
	var result = &sdkModel.CommandValue{}
	var err error
	var resTime = time.Now().UnixNano() / int64(time.Millisecond)

	switch deviceObject.Properties.Value.Type {
	case "Bool":
		result, err = sdkModel.NewBoolValue(&ro, resTime, reading.(bool))
	case "String":
		result = sdkModel.NewStringValue(&ro, resTime, reading.(string))
	case "Uint8":
		result, err = sdkModel.NewUint8Value(&ro, resTime, reading.(uint8))
	case "Uint16":
		result, err = sdkModel.NewUint16Value(&ro, resTime, reading.(uint16))
	case "Uint32":
		result, err = sdkModel.NewUint32Value(&ro, resTime, reading.(uint32))
	case "Uint64":
		result, err = sdkModel.NewUint64Value(&ro, resTime, reading.(uint64))
	case "Int8":
		result, err = sdkModel.NewInt8Value(&ro, resTime, reading.(int8))
	case "Int16":
		result, err = sdkModel.NewInt16Value(&ro, resTime, reading.(int16))
	case "Int32":
		result, err = sdkModel.NewInt32Value(&ro, resTime, reading.(int32))
	case "Int64":
		result, err = sdkModel.NewInt64Value(&ro, resTime, reading.(int64))
	case "Float32":
		result, err = sdkModel.NewFloat32Value(&ro, resTime, reading.(float32))
	case "Float64":
		result, err = sdkModel.NewFloat64Value(&ro, resTime, reading.(float64))
	default:
		err = fmt.Errorf("return result fail, none supported value type: %v", deviceObject.Properties.Value.Type)
	}

	return result, err
}
```

===================================================================

**I send the data ` {"name":"test-device","cmd":"speed","speed":12}` to DataTopic, the type of `response["speed"] ` is float64 via `json.Unmarshal(message.Payload(), &response)`. 
In this way, both int64 and int32 will be unified into float64. So, It needs to convert the reading into a data type defined in valueDescriptor.
In this case, the type of speed is int64 in valueDescriptor. So it will run `case "Int64":
		result, err = sdkModel.NewInt64Value(&ro, resTime, reading.(int64))`. Howerver, this will lead to panic : panic: interface conversion: interface {} is float64, not int64.   I hope that I can pay attention and fix such bugs as soon as possible.** 

In order to verify that converting reading is the wrong way, I  do a simple test.

```
package main

import (
	"encoding/json"
	"fmt"
	"reflect"
)

func main() {

	var response map[string]interface{}
	a := []byte(`{"name":"test-device","cmd":"speed","speed":12}`)
	json.Unmarshal(a, &response)
	//reading := response["speed"].(int64) // panic: interface conversion: interface {} is float64, not int64
	reading := int64(response["speed"].(float64))
	fmt.Println(reading)  // 12
	fmt.Println(reflect.TypeOf(reading)) // int64

}
```

**Comment by weichou1229** [comment]
@AhaEdgar  Golang will recognize it as float or int. I have created an issue https://github.com/edgexfoundry/device-mqtt-go/issues/6 and a PR https://github.com/edgexfoundry/device-mqtt-go/pull/11, please feel free to review or test my branch if you like.

**Comment by cloudxxx8** [comment]
@AhaEdgar 
Thanks for reporting this issue.
We have made lots of data type checking and transformation #11, and it also covers this issue.
Could you please help try again and see whether we can close this issue?
