### ISSUE TITLE
receipt of non-float number data will cause a panic in newResult function

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-mqtt-go#13]
The newResult function of driver.go will always fail if the reading is something other than a string or float64.  This is because the JSON unmarshaling will always interpret any number as a float64 (see https://golang.org/pkg/encoding/json/#Unmarshal).  Therefore, the type of the reading in the newResult function for any number (whether int, uint, etc.) will always be a float64 and cause a panic in the checks.  Best I could do was just assume that the profileValueType for the data was going to be correct and cast to the appropriate type.

func newResult(deviceObject models.DeviceObject, ro models.ResourceOperation, reading interface{}) (*sdkModel.CommandValue, error) {
	var result = &sdkModel.CommandValue{}
	var err error
	var resTime = time.Now().UnixNano() / int64(time.Millisecond)
	var profileValueType = strings.ToLower(deviceObject.Properties.Value.Type)

	switch profileValueType {
	case "bool":
		result, err = sdkModel.NewBoolValue(&ro, resTime, reading.(bool))
	case "string":
		result = sdkModel.NewStringValue(&ro, resTime, reading.(string))
	case "uint8":
		result, err = sdkModel.NewUint8Value(&ro, resTime, uint8(reading.(float64)))
	case "uint16":
		result, err = sdkModel.NewUint16Value(&ro, resTime, uint16(reading.(float64)))
	case "uint32":
		result, err = sdkModel.NewUint32Value(&ro, resTime, uint32(reading.(float64)))
	case "uint64":
		result, err = sdkModel.NewUint64Value(&ro, resTime, uint64(reading.(float64)))
	case "int8":
		result, err = sdkModel.NewInt8Value(&ro, resTime, int8(reading.(float64)))
	case "int16":
		result, err = sdkModel.NewInt16Value(&ro, resTime, int16(reading.(float64)))
	case "int32":
		result, err = sdkModel.NewInt32Value(&ro, resTime, int32(reading.(float64)))
	case "int64":
		result, err = sdkModel.NewInt64Value(&ro, resTime, int64(reading.(float64)))
	case "float32":
		result, err = sdkModel.NewFloat32Value(&ro, resTime, reading.(float32))
	case "float64":
		result, err = sdkModel.NewFloat64Value(&ro, resTime, reading.(float64))
	default:
		err = fmt.Errorf("return result fail, none supported value type: %v", deviceObject.Properties.Value.Type)
	}

	return result, err
}

**Comment by weichou1229** [comment]
Yes, you're right. I reproduce this error by MQTT client tool. 

Simulate an async value with the terminal tool:
```
./mosquitto_pub -t DataTopic -m '{"name":"MQTT test device","cmd":"randIntNum","method":"get","randIntNum":123}'
```
It throw error:
```
panic: interface conversion: interface {} is float64, not int64

goroutine 67 [running]:
github.com/edgexfoundry/device-mqtt-go/internal/driver.checkValueInRange(0xc00015e1e0, 0x5, 0x14bd9a0, 0x7, 0x14fa9a0, 0xc00015e1c0, 0x14fa900)
	/Users/bruce/go/src/github.com/edgexfoundry/device-mqtt-go/internal/driver/driver.go:530 +0x1536
```
And I will work on this issue.
