### ISSUE TITLE
If Data is return 0,it will be error

### ISSUE THREAD

**Issue by zhanglu0704** [edgexfoundry/device-mqtt-go#143]
edgex-device-mqtt    | level=ERROR ts=2020-04-22T12:39:55.393093853Z app=edgex-device-mqtt source=driver.go:314 msg="parse reading fail. Reading 0 is out of the value type(11)'s range"
edgex-device-mqtt    | level=INFO ts=2020-04-22T12:39:55.393107833Z app=edgex-device-mqtt source=driver.go:122 msg="Handle read commands failed: parse reading fail. Reading 0 is out of the value type(11)'s range"

**Comment by weichou1229** [comment]
The error reason is similar to the issue https://github.com/edgexfoundry/device-sdk-go/issues/358
The device service should modify the value checking function's comparing condition.
