### ISSUE TITLE
Parsing data from Device MQTT test: ERROR

### ISSUE THREAD

**Issue by MAISDUSE** [edgexfoundry/device-mqtt-go#147]
When I subscribe to a broker MQTT, I can parse my data: No DeviceObject found.
Can someone help me to configure this device MQTT?
Need I to modify something to use the Device MQTT test?
Thanks
M

**Comment by cloudxxx8** [comment]
May I know the data model or format you are using?
This repository is a reference implementation, and the accepted format is fixed.
https://docs.edgexfoundry.org/1.2/examples/Ch-ExamplesAddingMQTTDevice/

You may try the commercial version if you need more flexible format support in MQTT.

**Comment by MAISDUSE** [comment]
I send this via MQTT : {"name":"MQTT test device","cmd":"val","val":"56"}
And I use the exemple device from device-mqtt-go/cmd/res/example with almost no modification in the .yml and .toml.
But when the device MQTT read the data, it cannot find the device corresponding to the name "MQTT test device"
Where should I configure this?
Thanks
M

**Comment by weichou1229** [comment]
If you go through the doc,
1.The device name is come from `res/example/configuration.toml`
```
# Pre-define Devices
[[DeviceList]]
  Name = 'MQTT-test-device'
```
 2.`val` should equal to the device profile's device resource name

**Comment by MAISDUSE** [comment]
With the doc I got some error when the device read the sending data ({"name":"MQTT-test-device","cmd":"randfloat32","randfloat32":"56.30"}). It is the good device name and ressource name but : 
level=ERROR ts=2020-05-26T07:01:28.523720796Z app=edgex-device-mqtt source=managedprofiles.go:144 msg="retrieving DeviceResource - Device MQTT-test-device not found"
level=WARN ts=2020-05-26T07:01:28.563690621Z app=edgex-device-mqtt source=incominglistener.go:79 msg="[Incoming listener] Incoming reading ignored. No DeviceObject found : topic=MathTopic msg={\"name\":\"MQTT-test-device\",\"cmd\":\"randfloat32\",\"randfloat32\":\"56.30\"}"

Have you any idea?
Thanks
M

**Comment by kurokobo** [comment]
You can get a list of registered devices by `GET`ting the API of the metadata service. 

`curl -s http://localhost:48081/api/v1/device`

Is your device `MQTT-test-device` included correctly in the list?

**Comment by MAISDUSE** [comment]
My device MQTT is running but it isn't in the device list from the API call. 
 http://localhost:48081/api/v1/device
but he is in the list of device service: http://localhost:48081/api/v1/deviceservice

    {
        "created": 1590674547207,
        "modified": 1590674547207,
        "origin": 1590674547205,
        "id": "840adabd-5289-4c34-8321-d0d83bb334f7",
        "name": "edgex-device-mqtt",
        "operatingState": "ENABLED",
        "addressable": {
            "created": 1590674547203,
…
            "url": "http://localhost:49982/api/v1/callback"
        },
        "adminState": "UNLOCKED"
    }
]


Should I register him manually, or integrate it in the docker-compose.yml file?

**Comment by kurokobo** [comment]
If your device isn't in the list, maybe your `configuration.toml` is not read on its startup.

The important things are:

* The place of `configuration.toml` which includes `[[DeviceList]]` for your `MQTT-test-device`
* `volumes` and `entrypoint` for MQTT device service in the `docker-compose.yml`

If you are using Fuji release, please refer to the [official examples](https://fuji-docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html).

As this example shows, place your `configuration.toml` under `mqtt` directory:

```
- device-service-demo
  |- docker-compose.yml
  |- mqtt
     |- configuration.toml
     |- mqtt.test.device.profile.yml
```

and mount `mqtt` directory as `/custom-config` in the `docker-compose.yml`:

```
  volumes:
    ...
    - ./mqtt:/custom-config
```

and specify `/custom-config` as `confdir` in `entrypoint`:

```
  entrypoint:
    - /device-mqtt
    - --registry=consul://edgex-core-consul:8500
    - --confdir=/custom-config
```

If you are using Geneva release, maybe [my sample configuration](https://gist.github.com/kurokobo/079faae1c739c27bded7a2e3e92b6fab) will help you. It is almost same as Fuji, but there are some diferrences in the `entrypoint` and `configuration.toml`.

**Comment by MAISDUSE** [comment]
I am on fuji,
Thanks for this explanation, I was just doing it: 
I add the config in docker-compose.yml, exactly like you said and like the docs.
I add the 2 files for config in /mqtt. (.yml & .toml)

But when I do the, my device MQTT doesn't start.
Is this really running my device MQTT from sources?

                Name                              Command               State                       Ports                    
-----------------------------------------------------------------------------------------------------------------------------edgex-device-mqtt                      /device-mqtt --registry=co ...   Exit 1                                               


M

**Comment by kurokobo** [comment]
Please investigate the logs by running `docker logs edgex-device-mqtt`. I guess something is wrong in your configuration file...?

**Comment by MAISDUSE** [comment]
You were right, I got some errors:

~$ docker logs edgex-device-mqtt
Init: useRegistry: consul://edgex-core-consul:8500 profile:  confDir: /custom-config
Check registry is up... http://edgex-core-consul:8500
Pushing configuration into Registry...
Loading configuration from: /custom-config/configuration.toml

error loading config file: could not register service with Registry: Put http://localhost:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: connect: connection refused

**Comment by kurokobo** [comment]
If your `configuration.toml` is based on [this file](https://github.com/edgexfoundry/device-mqtt-go/blob/master/cmd/res/example/configuration.toml), it's not suite to use in docker container because all of hostname defined as `localhost`.

Please copy whole of `configuration.toml` from [the example](https://fuji-docs.edgexfoundry.org/Ch-ExamplesAddingMQTTDevice.html) and modify it to suite your environment.

**Comment by MAISDUSE** [comment]
ok, that is what I was doing first, just build and running from the sources.
so I comment the part on docker-compose.yml and I run my device MQTT from sources.
And if I do it, I got the issue at top of this conversation.

**Comment by kurokobo** [comment]
...Ah, sorry for the misunderstanding.
I've never tried that but I think maybe you should pass some arguments like `--confdir` like you specified in `entrypoint` in the `dokcer-compose.yml` when running your own `device-mqtt`.

**Comment by kurokobo** [comment]
In my environment, first time it shows error. But once exit with CTRL+C and simply run again, it works.
🤔

```bash
$ git clone https://github.com/edgexfoundry/device-mqtt-go.git
$ cd device-mqtt-go
$ make build
$ cd cmd/

# first time to run, new device is added successfully, but incoming reading ignored.
$ ./device-mqtt --confdir=./res/example
...
level=DEBUG ts=2020-05-28T16:24:25.340375672Z app=edgex-device-mqtt source=devices.go:22 msg="Loading pre-define Devices from configuration"
level=DEBUG ts=2020-05-28T16:24:25.340424505Z app=edgex-device-mqtt source=devices.go:28 msg="Device MQTT-test-device doesn't exist, creating a new one"
level=DEBUG ts=2020-05-28T16:24:25.340805606Z app=edgex-device-mqtt source=devices.go:60 msg="Adding Device:...
...
level=ERROR ts=2020-05-28T16:24:30.004836961Z app=edgex-device-mqtt source=managedprofiles.go:144 msg="retrieving DeviceResource - Device MQTT-test-device not found"
level=WARN ts=2020-05-28T16:24:30.004871945Z app=edgex-device-mqtt source=incominglistener.go:79 msg="[Incoming listener] Incoming reading ignored. No DeviceObject found : topic=DataTopic msg={\"name\":\"MQTT-test-device\",\"cmd\":\"randfloat32\",\"randfloat32\":\"27.2\"}"
...

# exit with CTRL+C, and simply run again, works good
$ ./device-mqtt --confdir=./res/example
...
level=INFO ts=2020-05-28T16:26:30.005008923Z app=edgex-device-mqtt source=incominglistener.go:100 msg="[Incoming listener] Incoming reading received: topic=DataTopic msg={\"name\":\"MQTT-test-device\",\"cmd\":\"randfloat32\",\"randfloat32\":\"26.1\"}"
level=DEBUG ts=2020-05-28T16:26:30.005354945Z app=edgex-device-mqtt source=utils.go:84 correlation-id=767e2cd3-e9d8-40ce-aea0-91bbfd9b3523 msg="SendEvent: EventClient.MarshalEvent encoded event"
level=INFO ts=2020-05-28T16:26:30.008087298Z app=edgex-device-mqtt source=utils.go:94 Content-Type=application/json correlation-id=767e2cd3-e9d8-40ce-aea0-91bbfd9b3523 msg="SendEvent: Pushed event to core data"
...
```

**Comment by MAISDUSE** [comment]
Oh,
Thanks, I didn't use the --confdir.
Now it's working!

Thank you kurokobo.

**Comment by MAISDUSE** [comment]
Thanks for your help, I got another question.
If I run the device MQTT from sources, can I see it in consul?

**Comment by cloudxxx8** [comment]
You need to add flag for starting
https://github.com/edgexfoundry/device-mqtt-go/blob/8b9d4518ce44b452ea6e7170c38b8c7009d29236/Dockerfile#L49

edgex-core-consul should be replaced by the Consul IP address

Also, please update SDK to v1.2.2-dev.2

**Comment by MAISDUSE** [comment]
I am using the fuji version of the device-mqtt-go from sources nothing is on docker-compose.yml because I do it on local.
If I use :
ENTRYPOINT ["/device-mqtt","--cp=consul://127.0.0.1:8500","--registry","--confdir=/res/example"] 
It should work?

**Comment by cloudxxx8** [comment]
not exactly, it depends on how you deploy your services
It won't work if you are using container environment, because 127.0.01 is the device-mqtt container itself

**Comment by MAISDUSE** [comment]
I don't understand very well.
Can I see the Health of my device MQTT if I run from sources?
I work in a hybrid environment, all EdgeX from docker and just the device-mqtt from sources.
So if I do that, I can't see my device in consul.

**Comment by cloudxxx8** [comment]
running device-mqtt from source is fine.  the point is the device-mqtt can connect to Consul with the right address.  if you make the correct port mapping of Consul container, 127.0.0.1 should work.

**Comment by MAISDUSE** [comment]
HI,
Thanks for all your help. It was very helpful.
I got a last question, If I want to run a docker version of the device MQTT go, I need to configure my docker-compose to use a confdir like this?

 device-mqtt:
   image: edgexfoundry/docker-device-mqtt-go:1.1.0
   ports:
     - "49982:49982"
   container_name: edgex-device-mqtt
   hostname: edgex-device-mqtt
   networks:
     - edgex-network
   volumes:
     - db-data:/data/db
     - log-data:/edgex/logs
     - consul-config:/consul/config
     - consul-data:/consul/data
     - ./mqtt:/custom-config
   depends_on:
     - data
     - command
   entrypoint:
     - /device-mqtt
     - --registry=consul://edgex-core-consul:8500
     - --confdir=/custom-config

And when I do it, I go an Exit Code 1 that Indicates a failure due to an application error.
How can I fix this?

I got this docker-compose logs:

edgex-device-mqtt    | Init: useRegistry: consul://edgex-core-consul:8500 profile:  confDir: /custom-config
edgex-device-mqtt    | Check registry is up... http://edgex-core-consul:8500
edgex-device-mqtt    | Pushing configuration into Registry...
edgex-device-mqtt    | Loading configuration from: /custom-config/configuration.toml
edgex-device-mqtt    | 
edgex-device-mqtt    | error loading config file: could not register service with Registry: Put http://localhost:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: connect: connection refused
edgex-device-mqtt    | Init: useRegistry: consul://edgex-core-consul:8500 profile:  confDir: /custom-config
edgex-device-mqtt    | Check registry is up... http://edgex-core-consul:8500
edgex-device-mqtt    | error loading config file: could not register service with Registry: Put http://localhost:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: connect: connection refused
edgex-device-mqtt    | Init: useRegistry: consul://edgex-core-consul:8500 profile:  confDir: /custom-config
edgex-device-mqtt    | Check registry is up... http://edgex-core-consul:8500
edgex-device-mqtt    | error loading config file: could not register service with Registry: Put http://localhost:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: connect: connection refused


M

**Comment by kurokobo** [comment]
If it's ok for you to use the [default configuration file which included in the container image](https://github.com/edgexfoundry/device-mqtt-go/blob/956ca6b6e476ad52eb19b4a5dcfc7810084d653f/cmd/res/docker/configuration.toml), you don't need to specify your own configuration file by `confdir`.

But in most cases, in my understanding, you have to specify your own configuration file or build your own container image with your own configuration file because the device service can't reach the the broker with default values and you can't override those values by environment variables. This is one of the restrictions of fuji release.

**Comment by kurokobo** [comment]
And for the second question, in fuji release, the configuration file which should be used is different for [running in docker](https://github.com/edgexfoundry/device-mqtt-go/blob/956ca6b6e476ad52eb19b4a5dcfc7810084d653f/cmd/res/docker/configuration.toml) and [running on your host](https://github.com/edgexfoundry/device-mqtt-go/blob/956ca6b6e476ad52eb19b4a5dcfc7810084d653f/cmd/res/configuration.toml). The differences are `Host` value.
This is also one of the restrictions of fuji release.

I guess you are using same configuration file that used when you built and run not in the container but on your host...? The log shows `http://localhost:8500/...`.
You should replace the values for all of `Host` from `localhost` to the container name as [this file](https://github.com/edgexfoundry/device-mqtt-go/blob/956ca6b6e476ad52eb19b4a5dcfc7810084d653f/cmd/res/docker/configuration.toml).

**Comment by kurokobo** [comment]
...Just for your information, alternatively, you can use geneva version of `docker-device-mqtt-go:1.2.0` with existing fuji release.
In `1.2.0`, the restrictions that I mentioned are resolved :laughing: You can run device service without using `confdir`, override any values except for `DeviceList` by environment variables (this is the recommended way), register your device-profile and devices by APIs.

**Comment by MAISDUSE** [comment]
Thanks a lot.
I still use Fuji version, but with the good configuration.toml
My device is running from docker but I still got Errors:
$ docker-compose logs device-mqtt
...
edgex-device-mqtt    | level=INFO ts=2020-06-04T13:00:24.422899695Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@0.0.0.0:18883 clientID=CommandResponseSubscriber "
edgex-device-mqtt    | level=INFO ts=2020-06-04T13:00:24.422946804Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@0.0.0.0:18883 clientID=IncomingDataSubscriber "
edgex-device-mqtt    | panic: start command response Listener failed, please check MQTT broker settings are correct, Network Error : dial tcp 0.0.0.0:18883: connect: connection refused

Have you an idea ?
M.

**Comment by kurokobo** [comment]
Instead of 0.0.0.0, specify the IP address of the host on which the broker is running.

**Comment by MAISDUSE** [comment]
If the broker is running on the same machine,

edgex-device-mqtt    | level=INFO ts=2020-06-04T13:22:23.553079993Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@127.0.0.1:18883 clientID=CommandResponseSubscriber "
edgex-device-mqtt    | level=INFO ts=2020-06-04T13:22:23.553345748Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@127.0.0.1:18883 clientID=IncomingDataSubscriber "
edgex-device-mqtt    | panic: start incoming data Listener failed, please check MQTT broker settings are correct, Network Error : dial tcp 127.0.0.1:18883: connect: connection refused

**Comment by kurokobo** [comment]
No, not 0.0.0.0, not 127.0.0.1, but some concrete IP address like 192.168.0.100 or 172.30.190.12.

Both 0.0.0.0 and 127.0.0.1 refer only to the IP address of the container itself, not your broker.

**Comment by MAISDUSE** [comment]
Thanks, I think I got the correct address, but I got new errors.

edgex-device-mqtt    | level=INFO ts=2020-06-04T14:02:35.448135459Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@192.168.1.29:18883 clientID=CommandResponseSubscriber "
edgex-device-mqtt    | level=INFO ts=2020-06-04T14:02:35.448657595Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@192.168.1.29:18883 clientID=IncomingDataSubscriber "
edgex-device-mqtt    | level=INFO ts=2020-06-04T14:02:35.452769677Z app=edgex-device-mqtt source=service.go:127 msg="Service started in: 363.635614ms"
edgex-device-mqtt    | panic: start command response Listener failed, please check MQTT broker settings are correct, Network Error : %!s(<nil>)

**Comment by kurokobo** [comment]
Are the MQTT broker settings correct? Can you subscribe to the same broker using the same IP address, port, credentials, and topic by any other MQTT client like mosquitto-client?

**Comment by MAISDUSE** [comment]
Big thank you,
I just swap the IP address of my computer to the broker one and its works.
My device MQTT is reading messages from the broker on port 1883 and Consul see its health status.
But the device didn't parse message because he didn't recognize the device name.

edgex-device-mqtt    | level=ERROR ts=2020-06-05T07:41:18.441304449Z app=edgex-device-mqtt source=managedprofiles.go:144 msg="retrieving DeviceResource - Device MQTT-test-device not found"
edgex-device-mqtt    | level=WARN ts=2020-06-05T07:41:18.441630592Z app=edgex-device-mqtt source=incominglistener.go:79 msg="[Incoming listener] Incoming reading ignored. No DeviceObject found : topic=DataTopic msg={\"name\":\"MQTT-test-device\",\"cmd\":\"va:49:mdb_simu_var1\",\"va:49:mdb_simu_var1\":\"2\"}"

So I add the DeviceList to the configuration.toml and 0 evolution.
Need I to modify something else?

M

**Comment by kurokobo** [comment]
Could you try completely cleaning up your environment including persistent volumes, then start it again, and watch the logs by running as follows:

```
docker-compose down --volumes
docker-compose up -d
docker logs -f edgex-device-mqtt
```

If your `DeviceList` is loaded correctly, the logs should show up the progress of adding the device.
And ensure that the device is registered or not by querying the metadata API.

**Comment by MAISDUSE** [comment]
Oh,
You were right, I got this issue : 
edgex-device-mqtt    | level=ERROR ts=2020-06-08T06:47:01.315403254Z app=edgex-device-mqtt source=devices.go:43 msg="Device Profile Test.Device.MQTT.Profile doesn't exist for Device MQTT-test-device"
edgex-device-mqtt    | level=ERROR ts=2020-06-08T06:47:01.315427266Z app=edgex-device-mqtt source=devices.go:31 msg="creating Device from config failed: MQTT-test-device"

And the device doesn't appear in the device list (API)

My files tree is: 
docker-compose.yml
mqtt
|_configuration.toml
|_mqtt.test.device.profile.yml


and in configuration.toml, I define my device like this: 

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./"

[Logging]
EnableRemote = true
File = "./device-mqtt.log"

[Writable]
LogLevel = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "MQTT-test-device"
  Profile = "Test.Device.MQTT.Profile"
  Description = "MQTT device is created for test purpose"
  Labels = [ "MQTT", "test"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "172.17.0.1"
       Port = "1883"
       ClientId = "CommandPublisher"
       User = "admin"
       Password = "public"
       Topic = "CommandTopic"



Thank you for your help.
M.

**Comment by cloudxxx8** [comment]
You need to modify ProfilesDir to the right location.  The profile might not be loaded.  It should also be "/custom-config", not "./"

**Comment by MAISDUSE** [comment]
With /custom config I don't have the same issue, 
It seems that don't load any device profiles 

edgex-device-mqtt    | Init: useRegistry: consul://edgex-core-consul:8500 profile:  confDir: /custom-config
edgex-device-mqtt    | Check registry is up... http://edgex-core-consul:8500
edgex-device-mqtt    | Register in registry...
edgex-device-mqtt    | Calling service.Start.
edgex-device-mqtt    | EnableRemote is true, using remote logging service
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:12.795298909Z app=edgex-device-mqtt source=init.go:138 msg="Check Metadata service's status ..."
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:12.795572884Z app=edgex-device-mqtt source=init.go:138 msg="Check Data service's status ..."
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:12.796431793Z app=edgex-device-mqtt source=init.go:48 msg="Service clients initialize successful."
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:12.796658101Z app=edgex-device-mqtt source=loader.go:247 msg="listen for config changes from Registry"
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:12.797058218Z app=edgex-device-mqtt source=loader.go:271 msg="Writeable configuration has been updated. Setting log level to INFO"
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.188540266Z app=edgex-device-mqtt source=service.go:146 msg="Device Service  doesn't exist, creating a new one"
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.189949763Z app=edgex-device-mqtt source=service.go:202 msg="Addressable edgex-device-mqtt doesn't exist, creating a new one"
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.561568115Z app=edgex-device-mqtt source=service.go:96 msg="*Service Start() called, name=edgex-device-mqtt, version=1.1.0"
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.561656827Z app=edgex-device-mqtt source=service.go:100 msg="Listening on port: 49982"
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.563972112Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@172.17.0.1:1883 clientID=CommandResponseSubscriber "
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.564307739Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@172.17.0.1:1883 clientID=IncomingDataSubscriber "
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.585402414Z app=edgex-device-mqtt source=responselistener.go:52 msg="[Response listener] Start command response listening. "
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.586319068Z app=edgex-device-mqtt source=incominglistener.go:54 msg="[Incoming listener] Start incoming data listening. "
edgex-device-mqtt    | level=INFO ts=2020-06-08T08:46:13.708961773Z app=edgex-device-mqtt source=service.go:127 msg="Service started in: 1.473119971s"
edgex-device-mqtt    | level=ERROR ts=2020-06-08T08:46:45.811020907Z app=edgex-device-mqtt source=managedprofiles.go:144 msg="retrieving DeviceResource - Device MQTT-test-device not found"
edgex-device-mqtt    | level=WARN ts=2020-06-08T08:46:45.811101685Z app=edgex-device-mqtt source=incominglistener.go:79 msg="[Incoming listener] Incoming reading ignored. No DeviceObject found : topic=DataTopic msg={\"name\":\"MQTT-test-device\",\"cmd\":\"va:49:mdb_simu_var1\",\"va:49:mdb_simu_var1\":\"2\"}"

**Comment by cloudxxx8** [comment]
Your profile dir config is wrong.  There is no profile yaml in "./"

[Device]
DataTransform = true
InitCmd = ""
InitCmdArgs = ""
MaxCmdOps = 128
MaxCmdValueLen = 256
RemoveCmd = ""
RemoveCmdArgs = ""
**ProfilesDir = "./"**

Please change to 

[Device]
DataTransform = true
InitCmd = ""
InitCmdArgs = ""
MaxCmdOps = 128
MaxCmdValueLen = 256
RemoveCmd = ""
RemoveCmdArgs = ""
**ProfilesDir = "/custom-config"**

to match your volume mapping:

volumes:
- db-data:/data/db
- log-data:/edgex/logs
- consul-config:/consul/config
- consul-data:/consul/data
**- ./mqtt:/custom-config**

**Comment by MAISDUSE** [comment]
#################################################################
# My Device Services MQTT
#################################################################
  device-mqtt:
    image: edgexfoundry/docker-device-mqtt-go:1.1.0
    ports:
      - "49982:49982"
    container_name: edgex-device-mqtt
    hostname: edgex-device-mqtt
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./mqtt:/custom-config
    depends_on:
      - data
      - command
    entrypoint:
      - /device-mqtt
      - --registry=consul://edgex-core-consul:8500
      - --confdir=/custom-config


#################################################################
And my configuration.toml : 
#################################################################
[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/custom-config"

[Logging]
EnableRemote = true
File = "./device-mqtt.log"

[Writable]
LogLevel = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "MQTT-test-device"
  Profile = "Test.Device.MQTT.Profile"
  Description = "MQTT device is created for test purpose"
  Labels = [ "MQTT", "test"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "172.17.0.1"
       Port = "1883"
       ClientId = "CommandPublisher"
       User = "admin"
       Password = "public"
       Topic = "CommandTopic"

**Comment by MAISDUSE** [comment]
So it should work?

**Comment by MAISDUSE** [comment]
Ye I have tried, 
With ProfilesDir=/custom, I never load any profiles.

**Comment by MAISDUSE** [comment]
And no devices are registered in the API (http://localhost:48081/api/v1/device).
I prefer to use profiles in file for my use case.

**Comment by cloudxxx8** [comment]
I notice you are using consul.  It might load the old config from Consul.  Could you please try to remove this line from docker-compose file?
`- --registry=consul://edgex-core-consul:8500`

Or, try `docker-compose down -v `and restart again

**Comment by MAISDUSE** [comment]
I want to keep the consul registry.
So I try to remove all the containers and recreate it.

Just for my information, if you are not using consul, what can you use?

**Comment by cloudxxx8** [comment]
I meant just for verifying the issue, not removing that line permanently.
Even you remove all containers, the data is still in the volume, so you need to add -v flag for down.
docker-compose down -v

Or, you can verify whether the key/value store keeps the latest config you made.
`ProfilesDir = "/custom-config"`

**Comment by MAISDUSE** [comment]
You were right,
without the consul registry, it's WORKS!

**Comment by MAISDUSE** [comment]
So you have an idea why it doesn't work with?

**Comment by cloudxxx8** [comment]
Your old configuration has uploaded to Consul, so it loads configuration from Consul instead of the toml file each time.  You can clean up the containers and volumes by
`docker-compose down -v`

Or, you can manually modify the configuration form Consul's key/value store to
`ProfilesDir = "/custom-config"`

**Comment by MAISDUSE** [comment]
Thanks.
It works finally.

You save my day.

M.

**Comment by cloudxxx8** [comment]
no problem
