### ISSUE TITLE
[docker/snap] Self-signed broker/server TLS certificates are not supported

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-mqtt-go#161]
Version: 1.2.1

While investigating issue #157 I was able to get device-mqtt (running natively) to make a successful connection to a local broker on my machine running TLS. I used a self-signed certificate for the server, and thus had to add the CA to my local system first.

If device-mqtt is running in a docker image or snap, as both have static set of root CA certificates, the service would not be able to verify the incoming self-signed certificate.

In order to support this, the service would need new configuration which would allow either a new CA cert or directory containing CA certs to be added. These new configuration items would then be used to setup a custom TLSConfig for the client (https://golang.org/pkg/crypto/tls/#Config).

It looks like the app-functions-sdk already has support for this, so we should leverage if/when this issue is addressed:

https://docs.edgexfoundry.org/1.2/microservices/application/BuiltIn/#mqtt

**Comment by iain-anderson** [comment]
Depends on https://github.com/edgexfoundry/device-sdk-go/issues/564

**Comment by lindseysimple** [comment]
Snap has been removed from EdgeX, closing the issue.
