### ISSUE TITLE
Errors in the configuration.toml file causing startup issues

### ISSUE THREAD

**Issue by M1TR** [edgexfoundry/device-mqtt-go#18]
In multiple places in the _configuration.toml_ file, instead of the relevant service URL such as _edgex-core-consul_, "localhost" is specified. This causes the service to crash on startup.
This issue is present in the file inside the **/cmd/res** and **/cmd/res/example** folders. The file in the **/cmd/res/docker** folder is configured correctly.

**Comment by weichou1229** [comment]
@M1TR We specify "edgex-core-consul" or "edgex-core-data" as host when deploy EdgeX into docker environment.
But we can deploy EdgeX without docker, so we use "localhost".

**Comment by M1TR** [comment]
@weichou1229 I checked the other device services to see if this convention is followed everywhere. **device-random** and **device-modbus** are not using "localhost" like this, so I thought that maybe this is an error.
But thanks for the clarification! Appreciate it.
