### ISSUE TITLE
device-mqtt-go version 1.3.1 crashed

### ISSUE THREAD

**Issue by tianxingguo** [edgexfoundry/device-mqtt-go#211]
tried to run device-mqtt-go, got crashed when startup it:

level=INFO ts=2021-02-25T12:10:29.994664081Z app=edgex-device-mqtt source=config.go:193 msg="Loaded configuration from /res/configuration.toml"
level=INFO ts=2021-02-25T12:10:29.996849613Z app=edgex-device-mqtt source=config.go:304 msg="Using local configuration from file (0 envVars overrides applied)"
level=INFO ts=2021-02-25T12:10:29.996875274Z app=edgex-device-mqtt source=httpserver.go:99 msg="Web server starting (0.0.0.0:49982)"
level=INFO ts=2021-02-25T12:10:29.99691938Z app=edgex-device-mqtt source=init.go:144 msg="Check Metadata service's status by ping..."
level=INFO ts=2021-02-25T12:10:29.997896831Z app=edgex-device-mqtt source=init.go:144 msg="Check Data service's status by ping..."
level=INFO ts=2021-02-25T12:10:30.004469015Z app=edgex-device-mqtt source=init.go:68 msg="Service clients initialize successful."
level=INFO ts=2021-02-25T12:10:30.007480209Z app=edgex-device-mqtt source=service.go:224 msg="Addressable edgex-device-mqtt exists, updating it"
level=DEBUG ts=2021-02-25T12:10:30.010677908Z app=edgex-device-mqtt source=service.go:155 msg="Trying to find DeviceService: edgex-device-mqtt"
level=INFO ts=2021-02-25T12:10:30.012739139Z app=edgex-device-mqtt source=service.go:177 msg="DeviceService edgex-device-mqtt exists, updating it"
level=INFO ts=2021-02-25T12:10:30.030222008Z app=edgex-device-mqtt source=restrouter.go:75 msg="Registering v2 routes..."
level=DEBUG ts=2021-02-25T12:10:30.030503094Z app=edgex-device-mqtt source=profiles.go:47 msg="created absolute path for loading pre-defined Device Profiles: /res"
level=INFO ts=2021-02-25T12:10:30.030714342Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandResponseSubscriber "
level=INFO ts=2021-02-25T12:10:30.030867048Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=IncomingDataSubscriber "
level=INFO ts=2021-02-25T12:10:30.034756978Z app=edgex-device-mqtt source=incominglistener.go:65 msg="[Incoming listener] Start incoming data listening. "
level=INFO ts=2021-02-25T12:10:30.03480844Z app=edgex-device-mqtt source=responselistener.go:63 msg="[Response listener] Start command response listening. "
level=DEBUG ts=2021-02-25T12:10:30.040514917Z app=edgex-device-mqtt source=devices.go:29 msg="Loading pre-define Devices from configuration"
level=DEBUG ts=2021-02-25T12:10:30.040558094Z app=edgex-device-mqtt source=devices.go:32 msg="Device MQTT-test-device exists, using the existing one"
level=DEBUG ts=2021-02-25T12:10:30.040581622Z app=edgex-device-mqtt source=devices.go:32 msg="Device MQ_DEVICE exists, using the existing one"
level=INFO ts=2021-02-25T12:10:30.040614825Z app=edgex-device-mqtt source=autodiscovery.go:32 msg="AutoDiscovery stopped: disabled by configuration"
level=INFO ts=2021-02-25T12:10:30.04062338Z app=edgex-device-mqtt source=autodiscovery.go:37 msg="AutoDiscovery stopped: interval error in configuration"
level=INFO ts=2021-02-25T12:10:30.040628232Z app=edgex-device-mqtt source=autodiscovery.go:41 msg="AutoDiscovery stopped: ProtocolDiscovery not implemented"
level=INFO ts=2021-02-25T12:10:30.040633085Z app=edgex-device-mqtt source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2021-02-25T12:10:30.040665704Z app=edgex-device-mqtt source=message.go:51 msg="Starting edgex-device-mqtt 1.3.1 "
level=INFO ts=2021-02-25T12:10:30.040672191Z app=edgex-device-mqtt source=message.go:55 msg="device mqtt started"
level=INFO ts=2021-02-25T12:10:30.040677625Z app=edgex-device-mqtt source=message.go:58 msg="Service started in: 47.566369ms"
level=DEBUG ts=2021-02-25T12:10:31.041564917Z app=edgex-device-mqtt source=executor.go:55 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandfloat64\"}"
level=DEBUG ts=2021-02-25T12:10:31.041631543Z app=edgex-device-mqtt source=command.go:276 msg="Handler - execReadCmd: deviceResource: randfloat64"
level=DEBUG ts=2021-02-25T12:10:31.041785615Z app=edgex-device-mqtt source=command.go:283 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number with e notion\",\"name\":\"randfloat64\",\"properties\":{\"value\":{\"type\":\"Float64\",\"readWrite\":\"R\",\"minimum\":\"100.00\",\"maximum\":\"0.00\",\"defaultValue\":\"0.00\",\"size\":\"4\",\"floatEncoding\":\"eNotation\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2021-02-25T12:10:31.041809608Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandPublisher "
level=DEBUG ts=2021-02-25T12:10:31.041904236Z app=edgex-device-mqtt source=executor.go:55 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandfloat32\"}"
level=DEBUG ts=2021-02-25T12:10:31.04193301Z app=edgex-device-mqtt source=command.go:276 msg="Handler - execReadCmd: deviceResource: randfloat32"
level=DEBUG ts=2021-02-25T12:10:31.042053689Z app=edgex-device-mqtt source=command.go:283 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number with Base64 encoding\",\"name\":\"randfloat32\",\"properties\":{\"value\":{\"type\":\"Float32\",\"readWrite\":\"R\",\"minimum\":\"100.00\",\"maximum\":\"0.00\",\"defaultValue\":\"0.00\",\"size\":\"4\",\"floatEncoding\":\"Base64\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2021-02-25T12:10:31.04208235Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandPublisher "
level=INFO ts=2021-02-25T12:10:31.043749964Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"randfloat64\",\"method\":\"get\",\"uuid\":\"603793b776ae7600019f6db0\"}"
level=INFO ts=2021-02-25T12:10:31.044332697Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"randfloat32\",\"method\":\"get\",\"uuid\":\"603793b776ae7600019f6db1\"}"
level=WARN ts=2021-02-25T12:10:31.044479964Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-02-25T12:10:31.04643585Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-02-25T12:10:31.048790386Z app=edgex-device-mqtt source=driver.go:294 msg="Reconnection failed : Network Error : %!s(<nil>)"
level=WARN ts=2021-02-25T12:10:31.048858157Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-02-25T12:10:31.049043091Z app=edgex-device-mqtt source=driver.go:296 msg="Reconnection sucessful"
level=WARN ts=2021-02-25T12:10:31.050700686Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-02-25T12:10:31.050957187Z app=edgex-device-mqtt source=driver.go:296 msg="Reconnection sucessful"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x700b7c]
goroutine 125 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost(0xc00048a000, 0x9ef080, 0xc0000c65f0)
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/client.go:504 +0x5c
created by github.com/eclipse/paho%2emqtt%2egolang.errorWatch
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/net.go:352 +0x1cf

**Comment by weichou1229** [comment]
What is the edgex version?
Could you please provide the steps to recreate issue?

**Comment by edgego** [comment]
version: edgexfoundry/docker-device-mqtt-go:1.3.1, today crashed again:


level=INFO ts=2021-03-18T01:05:27.680728486Z app=edgex-device-mqtt source=config.go:193 msg="Loaded configuration from /res/configuration.toml"
level=INFO ts=2021-03-18T01:05:27.682467352Z app=edgex-device-mqtt source=config.go:304 msg="Using local configuration from file (0 envVars overrides applied)"
level=INFO ts=2021-03-18T01:05:27.682500298Z app=edgex-device-mqtt source=httpserver.go:99 msg="Web server starting (0.0.0.0:49982)"
level=INFO ts=2021-03-18T01:05:27.682558059Z app=edgex-device-mqtt source=init.go:144 msg="Check Metadata service's status by ping..."
level=INFO ts=2021-03-18T01:05:27.682689701Z app=edgex-device-mqtt source=init.go:144 msg="Check Data service's status by ping..."
level=INFO ts=2021-03-18T01:05:27.68960404Z app=edgex-device-mqtt source=init.go:68 msg="Service clients initialize successful."
level=INFO ts=2021-03-18T01:05:27.69688448Z app=edgex-device-mqtt source=service.go:224 msg="Addressable edgex-device-mqtt exists, updating it"
level=DEBUG ts=2021-03-18T01:05:27.702743172Z app=edgex-device-mqtt source=service.go:155 msg="Trying to find DeviceService: edgex-device-mqtt"
level=INFO ts=2021-03-18T01:05:27.711618929Z app=edgex-device-mqtt source=service.go:177 msg="DeviceService edgex-device-mqtt exists, updating it"
level=INFO ts=2021-03-18T01:05:27.746536716Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandResponseSubscriber "
level=INFO ts=2021-03-18T01:05:27.746747071Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=IncomingDataSubscriber "
level=INFO ts=2021-03-18T01:05:27.746947605Z app=edgex-device-mqtt source=restrouter.go:75 msg="Registering v2 routes..."
level=DEBUG ts=2021-03-18T01:05:27.747520068Z app=edgex-device-mqtt source=profiles.go:47 msg="created absolute path for loading pre-defined Device Profiles: /res"
level=INFO ts=2021-03-18T01:05:27.750883606Z app=edgex-device-mqtt source=incominglistener.go:65 msg="[Incoming listener] Start incoming data listening. "
level=INFO ts=2021-03-18T01:05:27.750957254Z app=edgex-device-mqtt source=responselistener.go:63 msg="[Response listener] Start command response listening. "
level=DEBUG ts=2021-03-18T01:05:27.754275728Z app=edgex-device-mqtt source=devices.go:29 msg="Loading pre-define Devices from configuration"
level=DEBUG ts=2021-03-18T01:05:27.754395352Z app=edgex-device-mqtt source=devices.go:32 msg="Device MQTT-test-device exists, using the existing one"
level=DEBUG ts=2021-03-18T01:05:27.754405809Z app=edgex-device-mqtt source=devices.go:32 msg="Device MQ_DEVICE exists, using the existing one"
level=INFO ts=2021-03-18T01:05:27.754480238Z app=edgex-device-mqtt source=autodiscovery.go:32 msg="AutoDiscovery stopped: disabled by configuration"
level=INFO ts=2021-03-18T01:05:27.754491403Z app=edgex-device-mqtt source=autodiscovery.go:37 msg="AutoDiscovery stopped: interval error in configuration"
level=INFO ts=2021-03-18T01:05:27.754521627Z app=edgex-device-mqtt source=autodiscovery.go:41 msg="AutoDiscovery stopped: ProtocolDiscovery not implemented"
level=INFO ts=2021-03-18T01:05:27.754527658Z app=edgex-device-mqtt source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2021-03-18T01:05:27.754534072Z app=edgex-device-mqtt source=message.go:51 msg="Starting edgex-device-mqtt 1.3.1 "
level=INFO ts=2021-03-18T01:05:27.754539572Z app=edgex-device-mqtt source=message.go:55 msg="device mqtt started"
level=INFO ts=2021-03-18T01:05:27.754545619Z app=edgex-device-mqtt source=message.go:58 msg="Service started in: 75.078995ms"
level=DEBUG ts=2021-03-18T01:05:28.755372123Z app=edgex-device-mqtt source=executor.go:55 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandfloat64\"}"
level=DEBUG ts=2021-03-18T01:05:28.755426719Z app=edgex-device-mqtt source=executor.go:55 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandfloat32\"}"
level=DEBUG ts=2021-03-18T01:05:28.7554486Z app=edgex-device-mqtt source=command.go:276 msg="Handler - execReadCmd: deviceResource: randfloat64"
level=DEBUG ts=2021-03-18T01:05:28.755462639Z app=edgex-device-mqtt source=command.go:276 msg="Handler - execReadCmd: deviceResource: randfloat32"
level=DEBUG ts=2021-03-18T01:05:28.755718318Z app=edgex-device-mqtt source=command.go:283 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number with e notion\",\"name\":\"randfloat64\",\"properties\":{\"value\":{\"type\":\"Float64\",\"readWrite\":\"R\",\"minimum\":\"100.00\",\"maximum\":\"0.00\",\"defaultValue\":\"0.00\",\"size\":\"4\",\"floatEncoding\":\"eNotation\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2021-03-18T01:05:28.755819267Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandPublisher "
level=DEBUG ts=2021-03-18T01:05:28.755971202Z app=edgex-device-mqtt source=command.go:283 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number with Base64 encoding\",\"name\":\"randfloat32\",\"properties\":{\"value\":{\"type\":\"Float32\",\"readWrite\":\"R\",\"minimum\":\"100.00\",\"maximum\":\"0.00\",\"defaultValue\":\"0.00\",\"size\":\"4\",\"floatEncoding\":\"Base64\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2021-03-18T01:05:28.756034776Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandPublisher "
level=INFO ts=2021-03-18T01:05:28.7576596Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"randfloat64\",\"method\":\"get\",\"uuid\":\"6052a7582840320001dfdc38\"}"
level=INFO ts=2021-03-18T01:05:28.757726044Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"randfloat32\",\"method\":\"get\",\"uuid\":\"6052a7582840320001dfdc39\"}"
level=WARN ts=2021-03-18T01:05:28.758040902Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.75953244Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.760500111Z app=edgex-device-mqtt source=driver.go:294 msg="Reconnection failed : Network Error : %!s(<nil>)"
level=WARN ts=2021-03-18T01:05:28.760841957Z app=edgex-device-mqtt source=driver.go:294 msg="Reconnection failed : Network Error : %!s(<nil>)"
level=WARN ts=2021-03-18T01:05:28.760848891Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.76147096Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.76324701Z app=edgex-device-mqtt source=driver.go:294 msg="Reconnection failed : Network Error : %!s(<nil>)"
level=WARN ts=2021-03-18T01:05:28.763280243Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.763269671Z app=edgex-device-mqtt source=driver.go:296 msg="Reconnection sucessful"
level=WARN ts=2021-03-18T01:05:28.763366914Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.764828462Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.766304356Z app=edgex-device-mqtt source=driver.go:294 msg="Reconnection failed : Network Error : %!s(<nil>)"
level=WARN ts=2021-03-18T01:05:28.76636357Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.766750019Z app=edgex-device-mqtt source=driver.go:296 msg="Reconnection sucessful"
level=WARN ts=2021-03-18T01:05:28.767180774Z app=edgex-device-mqtt source=driver.go:294 msg="Reconnection failed : Network Error : %!s(<nil>)"
level=WARN ts=2021-03-18T01:05:28.767418731Z app=edgex-device-mqtt source=driver.go:296 msg="Reconnection sucessful"
level=WARN ts=2021-03-18T01:05:28.767647946Z app=edgex-device-mqtt source=driver.go:291 msg="Connection lost : EOF"
level=WARN ts=2021-03-18T01:05:28.770167795Z app=edgex-device-mqtt source=driver.go:296 msg="Reconnection sucessful"
level=INFO ts=2021-03-18T01:05:33.759597876Z app=edgex-device-mqtt source=driver.go:125 msg="Handle read commands failed: can not fetch command response: method=get cmd=randfloat32"
level=INFO ts=2021-03-18T01:05:33.759598237Z app=edgex-device-mqtt source=driver.go:125 msg="Handle read commands failed: can not fetch command response: method=get cmd=randfloat64"
level=ERROR ts=2021-03-18T01:05:33.759709673Z app=edgex-device-mqtt source=executor.go:58 msg="AutoEvent - error occurs when reading resource testrandfloat32"
level=DEBUG ts=2021-03-18T01:05:33.759747946Z app=edgex-device-mqtt source=utils.go:295 msg="Update of last connected times is disabled for: MQ_DEVICE"
level=DEBUG ts=2021-03-18T01:05:34.760239746Z app=edgex-device-mqtt source=executor.go:55 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandfloat32\"}"
level=DEBUG ts=2021-03-18T01:05:34.760512184Z app=edgex-device-mqtt source=command.go:276 msg="Handler - execReadCmd: deviceResource: randfloat32"
level=DEBUG ts=2021-03-18T01:05:34.760675353Z app=edgex-device-mqtt source=command.go:283 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number with Base64 encoding\",\"name\":\"randfloat32\",\"properties\":{\"value\":{\"type\":\"Float32\",\"readWrite\":\"R\",\"minimum\":\"100.00\",\"maximum\":\"0.00\",\"defaultValue\":\"0.00\",\"size\":\"4\",\"floatEncoding\":\"Base64\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2021-03-18T01:05:34.760956984Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandPublisher "
level=INFO ts=2021-03-18T01:05:34.76462502Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"randfloat32\",\"method\":\"get\",\"uuid\":\"6052a75e2840320001dfdc3a\"}"
level=INFO ts=2021-03-18T01:05:39.765842076Z app=edgex-device-mqtt source=driver.go:125 msg="Handle read commands failed: can not fetch command response: method=get cmd=randfloat32"
level=ERROR ts=2021-03-18T01:05:39.766368508Z app=edgex-device-mqtt source=executor.go:58 msg="AutoEvent - error occurs when reading resource testrandfloat32"
level=DEBUG ts=2021-03-18T01:05:39.766430948Z app=edgex-device-mqtt source=utils.go:295 msg="Update of last connected times is disabled for: MQ_DEVICE"
level=DEBUG ts=2021-03-18T01:05:40.766683169Z app=edgex-device-mqtt source=executor.go:55 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandfloat32\"}"
level=DEBUG ts=2021-03-18T01:05:40.766749498Z app=edgex-device-mqtt source=command.go:276 msg="Handler - execReadCmd: deviceResource: randfloat32"
level=DEBUG ts=2021-03-18T01:05:40.766795427Z app=edgex-device-mqtt source=command.go:283 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number with Base64 encoding\",\"name\":\"randfloat32\",\"properties\":{\"value\":{\"type\":\"Float32\",\"readWrite\":\"R\",\"minimum\":\"100.00\",\"maximum\":\"0.00\",\"defaultValue\":\"0.00\",\"size\":\"4\",\"floatEncoding\":\"Base64\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2021-03-18T01:05:40.766811467Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandPublisher "
level=INFO ts=2021-03-18T01:05:40.769844974Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"randfloat32\",\"method\":\"get\",\"uuid\":\"6052a7642840320001dfdc3b\"}"
level=INFO ts=2021-03-18T01:05:45.772965791Z app=edgex-device-mqtt source=driver.go:125 msg="Handle read commands failed: can not fetch command response: method=get cmd=randfloat32"
level=ERROR ts=2021-03-18T01:05:45.773302381Z app=edgex-device-mqtt source=executor.go:58 msg="AutoEvent - error occurs when reading resource testrandfloat32"
level=DEBUG ts=2021-03-18T01:05:45.773373442Z app=edgex-device-mqtt source=utils.go:295 msg="Update of last connected times is disabled for: MQ_DEVICE"
level=DEBUG ts=2021-03-18T01:05:46.774163563Z app=edgex-device-mqtt source=executor.go:55 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandfloat32\"}"
level=DEBUG ts=2021-03-18T01:05:46.774243121Z app=edgex-device-mqtt source=command.go:276 msg="Handler - execReadCmd: deviceResource: randfloat32"
level=DEBUG ts=2021-03-18T01:05:46.774281179Z app=edgex-device-mqtt source=command.go:283 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number with Base64 encoding\",\"name\":\"randfloat32\",\"properties\":{\"value\":{\"type\":\"Float32\",\"readWrite\":\"R\",\"minimum\":\"100.00\",\"maximum\":\"0.00\",\"defaultValue\":\"0.00\",\"size\":\"4\",\"floatEncoding\":\"Base64\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2021-03-18T01:05:46.774298532Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandPublisher "
level=INFO ts=2021-03-18T01:05:46.777609659Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"randfloat32\",\"method\":\"get\",\"uuid\":\"6052a76a2840320001dfdc3c\"}"
level=INFO ts=2021-03-18T01:05:51.779883284Z app=edgex-device-mqtt source=driver.go:125 msg="Handle read commands failed: can not fetch command response: method=get cmd=randfloat32"
level=ERROR ts=2021-03-18T01:05:51.780279337Z app=edgex-device-mqtt source=executor.go:58 msg="AutoEvent - error occurs when reading resource testrandfloat32"
level=DEBUG ts=2021-03-18T01:05:51.780312596Z app=edgex-device-mqtt source=utils.go:295 msg="Update of last connected times is disabled for: MQ_DEVICE"
level=DEBUG ts=2021-03-18T01:05:52.780466427Z app=edgex-device-mqtt source=executor.go:55 msg="AutoEvent - executing {\"frequency\":\"1s\",\"resource\":\"testrandfloat32\"}"
level=DEBUG ts=2021-03-18T01:05:52.780532892Z app=edgex-device-mqtt source=command.go:276 msg="Handler - execReadCmd: deviceResource: randfloat32"
level=DEBUG ts=2021-03-18T01:05:52.780591246Z app=edgex-device-mqtt source=command.go:283 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device random number with Base64 encoding\",\"name\":\"randfloat32\",\"properties\":{\"value\":{\"type\":\"Float32\",\"readWrite\":\"R\",\"minimum\":\"100.00\",\"maximum\":\"0.00\",\"defaultValue\":\"0.00\",\"size\":\"4\",\"floatEncoding\":\"Base64\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2021-03-18T01:05:52.78061228Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://admin:public@edgex-mqtt-broker:1883 clientID=CommandPublisher "
level=INFO ts=2021-03-18T01:05:52.783368591Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"randfloat32\",\"method\":\"get\",\"uuid\":\"6052a7702840320001dfdc3d\"}"
level=INFO ts=2021-03-18T01:05:57.78503317Z app=edgex-device-mqtt source=driver.go:125 msg="Handle read commands failed: can not fetch command response: method=get cmd=randfloat32"
level=ERROR ts=2021-03-18T01:05:57.785381442Z app=edgex-device-mqtt source=executor.go:58 msg="AutoEvent - error occurs when reading resource testrandfloat32"
level=DEBUG ts=2021-03-18T01:05:57.785467518Z app=edgex-device-mqtt source=utils.go:295 msg="Update of last connected times is disabled for: MQ_DEVICE"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ec426]

goroutine 224 [running]:
bytes.(*Buffer).WriteTo(0xc00054ae10, 0x0, 0x0, 0x40, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:239 +0x86
github.com/eclipse/paho.mqtt.golang/packets.(*PingreqPacket).Write(0xc00037a670, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/packets/pingreq.go:21 +0x71
github.com/eclipse/paho%2emqtt%2egolang.keepalive(0xc00000a3c0)
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/ping.go:57 +0x776
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.2.0/client.go:306 +0x8cb

**Comment by weichou1229** [comment]
@edgego 
Could you please provide the steps to recreate issue?

**Comment by edgego** [comment]
no special steps, just restart it, then the issue occurred.

**Comment by edgego** [comment]
probably network factor caused this.

**Comment by weichou1229** [comment]
@edgego  
Could you provide the steps and config to deploy the Edgex services? 
So I can try to recreate the issue and debug on my machine.

**Comment by dmocek-o** [comment]
I have a similar issue where device-mqtt is not as resilient as I think it should be.  In my case, device-mqtt is reporting the error below.  Instead of waiting, it exits.  This happened on a regular start of EdgeX Hanoi.  All I had to do was a 'docker-compose up -d device-mqtt' and it started fine.  This isn't something that should have to be done in a production environment.

...
level=ERROR ts=2021-06-08T18:43:30.154163807Z app=edgex-device-mqtt source=init.go:176 msg="edgex-core-metadata service is not registered. Might not have started... "
level=ERROR ts=2021-06-08T18:43:30.15612335Z app=edgex-device-mqtt source=init.go:176 msg=" edgex-core-data service not healthy..."
level=ERROR ts=2021-06-08T18:43:31.154525808Z app=edgex-device-mqtt source=init.go:139 msg="dependency Metadata service checking time out"
level=ERROR ts=2021-06-08T18:43:31.15633672Z app=edgex-device-mqtt source=init.go:139 msg="dependency Data service checking time out"
level=INFO ts=2021-06-08T18:43:31.156577838Z app=edgex-device-mqtt source=httpserver.go:116 msg="Web server shutting down"
level=INFO ts=2021-06-08T18:43:31.156797387Z app=edgex-device-mqtt source=httpserver.go:107 msg="Web server stopped"
level=INFO ts=2021-06-08T18:43:31.656864889Z app=edgex-device-mqtt source=httpserver.go:118 msg="Web server shut down"
level=INFO ts=2021-06-08T18:43:31.657016994Z app=edgex-device-mqtt source=bootstrap.go:131 msg="Un-Registering service from the Registry"

**Comment by cloudxxx8** [comment]
@dmocek-o it is as design.
Device Services need to register itself to core-metadata, and retrieve the current related Devices, Device Profiles, and Provision Watcher when they are starting up.  They need core-data to push event and retrieve ValueDescriptors, too.
In v2, the only dependency would be core-metadata

**Comment by dmocek-o** [comment]
Hi cloudxxx8.  I understand device services needs core-metadata, but I suggest giving device services more time to wait for core-metadata to become available.  device-mqtt is exiting with a normal startup of EdgeX.  That seems unacceptable.  It requires someone to re-start device-mqtt manually on the system.  The only reason core-metadata isn't up is all of the services are coming up and it takes a little more time for them to come up.  If device services would wait a bit longer, it would find core-metadata.  Another thing to consider is that this happened while running on a PC.  Not the best PC, but a PC.  What happens when it runs on a RaspberryPi or some other low powered device?  I think it will take even longer for core-metadata to come up.

**Comment by cloudxxx8** [comment]
@dmocek-o I understand your situation.  We have a default timeout, and it is 60 seconds.  The timeout is configurable with the environment variable.  You just need to add an environment variable in the docker-compose file to override the timeout.
Here is the example to extend the timeout to 120 seconds.
`EDGEX_STARTUP_DURATION: "120"`
Please make a try.

**Comment by dmocek-o** [comment]
Excellent...thanks.
