### ISSUE TITLE
Use postman put value , return Handler  'CredentialsPath' not exist

### ISSUE THREAD

**Issue by Haoyuli1990** [edgexfoundry/device-mqtt-go#213]
I use postman to put message:
http://192.168.2.146:48082/api/v1/device/name/mqtt_haoyul/command/testmessage 
but return:
Handler - execWriteCmd: error for Device: mqtt_haoyul cmd: testmessage, unable to load config, 'CredentialsPath' not exist /api/v1/device/18beb0e4-cde8-45ef-98e8-0a1cf8cfeb23/testmessage

what's CredentialsPath? How to fix it?
thanks.

**Comment by weichou1229** [comment]
> what's CredentialsPath? 

The **CredentialsPath** is used to store the username and password.

> How to fix it?

Could you check your configuration file or json body? You need to define the CredentialsPath for adding the new MQTT deivce.

```
    [DeviceList.Protocols.mqtt]
       ...
       CredentialsPath = 'credentials'
```
https://github.com/edgexfoundry/device-mqtt-go/blob/master/cmd/res/example/configuration-autoevents.toml#L77

```
[Writable]
LogLevel = 'INFO'
    [Writable.InsecureSecrets]
        [Writable.InsecureSecrets.MQTT]
        path = "credentials"
            [Writable.InsecureSecrets.MQTT.Secrets]
            username = ""
            password = ""
```
https://github.com/edgexfoundry/device-mqtt-go/blob/master/cmd/res/example/configuration-autoevents.toml#L4



```
# Driver configs
[Driver]
...
IncomingCredentialsPath = 'credentials'
...
ResponseCredentialsPath = 'credentials'
```
https://github.com/edgexfoundry/device-mqtt-go/blob/master/cmd/res/example/configuration-autoevents.toml#L92

**Comment by lenny-intel** [comment]
@Haoyuli1990, seems that you are using the latest device MQTT for the upcoming Ireland release with an old configuration file. These changes, as you see are NOT backwards compatible and require update to your configuration file. Please use the latest example configuration file in device MQTT and make any appropriate changes that you need for you use case.

**Comment by cloudxxx8** [comment]
Ireland release is under development, and we haven't made the corresponding change in device-mqtt.
Please use the Hanoi (tag v1.3.1) release for now.
Could you please let us know your issue recreate steps, including your environment and deployment way?

**Comment by Haoyuli1990** [comment]
> Ireland release is under development, and we haven't made the corresponding change in device-mqtt.
> Please use the Hanoi (tag v1.3.1) release for now.
> Could you please let us know your issue recreate steps, including your environment and deployment way?

I use Geneva 1.2.1, the default device-mqtt is work. Then I modified some code of device-mqtt and compiled it, but it was still this error after startup. If I want to modify some parameters of the code and compile, which version of device mqtt is better? Which version of device mqtt can run under which version of edgex after modification?

**Comment by cloudxxx8** [comment]
The best way is to use the same version.  If you use v1.3.1 device-mqtt, use the v1.3.1 edgex services

**Comment by Haoyuli1990** [comment]
> The best way is to use the same version. If you use v1.3.1 device-mqtt, use the v1.3.1 edgex services

For edgex service version v1.3.1, which branch of device-mqtt do I use to source code build?

**Comment by cloudxxx8** [comment]
please fork the repository and branch out from the tag v1.3.1

**Comment by lenny-intel** [comment]
@Haoyuli1990 , can this question be closed?

**Comment by iain-anderson** [comment]
closing as inactive
