### ISSUE TITLE
native compilation at raspberry pi 4 issue

### ISSUE THREAD

**Issue by Balaji-guru** [edgexfoundry/device-mqtt-go#255]
when doing native compilation rpi4 (arm64) and ./device-mqtt 

i am getting this error, help me to resolve

i not using store and forward so i have added EDGEX_SECURITY_SECRET_STORE=false  in ./res/configuration.toml

level=INFO ts=2021-05-25T13:56:57.862694952Z app=device-mqtt source=config.go:359 msg="Loaded service configuration from ./res/configuration.toml"
level=INFO ts=2021-05-25T13:56:57.865180208Z app=device-mqtt source=secret.go:49 msg="Creating SecretClient"
level=INFO ts=2021-05-25T13:56:57.865286059Z app=device-mqtt source=secret.go:56 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-05-25T13:56:57.865329689Z app=device-mqtt source=secret.go:68 msg="Attempting to create secret client"
level=WARN ts=2021-05-25T13:56:57.865374077Z app=device-mqtt source=secret.go:78 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
level=INFO ts=2021-05-25T13:56:58.865706531Z app=device-mqtt source=secret.go:56 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-05-25T13:56:58.866051213Z app=device-mqtt source=secret.go:68 msg="Attempting to create secret client"
level=WARN ts=2021-05-25T13:56:58.866174823Z app=device-mqtt source=secret.go:78 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
level=INFO ts=2021-05-25T13:56:59.866502217Z app=device-mqtt source=secret.go:56 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-05-25T13:56:59.866795678Z app=device-mqtt source=secret.go:68 msg="Attempting to create secret client"
level=WARN ts=2021-05-25T13:56:59.866895603Z app=device-mqtt source=secret.go:78 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
level=INFO ts=2021-05-25T13:57:00.867096642Z app=device-mqtt source=secret.go:56 msg="Reading secret store configuration and authentication token"
level=INFO ts=2021-05-25T13:57:00.867242752Z app=device-mqtt source=secret.go:68 msg="Attempting to create secret client"
level=WARN ts=2021-05-25T13:57:00.86731201Z app=device-mqtt source=secret.go:78 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"
level=INFO ts=2021-05-25T13:57:01.8675421Z app=device-mqtt source=secret.go:56 msg="Reading secret store configuration and authentication token"

**Comment by cloudxxx8** [comment]
EDGEX_SECURITY_SECRET_STORE is an environment variable, not configuration.
Please try to set this environment variable before running.

**Comment by lenny-intel** [comment]
@Balaji-guru , this question is very old. Can we close?

**Comment by iain-anderson** [comment]
closing as inactive
