### ISSUE TITLE
[Device MQTT] ProfilesDir  & DevicesDir  are not set and duplicate device names

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-mqtt-go#285]
ProfilesDir = './res/profiles'
DevicesDir = './res/devices'

Device name in both device files is the same. 
Do we need both? our can just have the AutoEvents commented out in the one file.

**Comment by weichou1229** [comment]
> Do we need both? our can just have the AutoEvents commented out in the one file.

I will removed the duplicated one.
