### ISSUE TITLE
How to configure mqtt through edgex using meta-edgex layer

### ISSUE THREAD

**Issue by Rohini8** [edgexfoundry/device-mqtt-go#326]
We integrated meta-edgex layer in yocto build for imx8 board. Ran the edgex-fuji-launch.sh script and all services are up. Then we ran device-mqtt-launch.sh script. It's showing the service is up and started publishing and listening. But we are not able to see the messages (from MQTT test device) in HiveMQ mqtt client. 
Please let us know how to configure mqtt service (configuration.toml file) to publish the message to MQTT broker and to check the messages using HiveMQ client.

Here by attaching the log on the board:
[Edgex-Mqtt-logs-on-imx8.txt](https://github.com/edgexfoundry/device-mqtt-go/files/7586029/Edgex-Mqtt-logs-on-imx8.txt)

**Comment by cloudxxx8** [comment]
MQTT Device Service is a south bound connector to connect the devices publishing MQTT message, so it won't publish data to northbound.  Please refer to the quick started guide:
https://docs.edgexfoundry.org/2.1/getting-started/quick-start/

**Comment by Rohini8** [comment]
https://docs.edgexfoundry.org/2.0/getting-started/quick-start/
As per the docker-compose.yml file (from the above link), microservice used to configure mqtt is "**edgex-app-mqtt**".

But in the meta-edgex layer (https://github.com/alihanyalcin/meta-edgex), the service we are running to configure mqtt  is "**edgex-device-mqtt**". 

May I know the difference between "**edgex-app-mqtt**" and "**edgex-device-mqtt**" ??

**Comment by cloudxxx8** [comment]
edgex-device-mqtt is responsible for communicating the southbound devices: https://docs.edgexfoundry.org/2.1/microservices/device/Ch-DeviceServices/

edgex-app-mqtt is an application service to export data to northbound:
https://docs.edgexfoundry.org/2.1/microservices/application/ApplicationServices/

**Comment by Rohini8** [comment]
Thank you for the information.
Is "edgex-app-mqtt" available in "Fuji" version of EdgeX?

**Comment by Rohini8** [comment]
Ok. We are trying to run edgex on Imx8qmmek board using meta-edgex layer.
Is there any way to enable "edgex-app-mqtt" in meta-edgex (https://github.com/alihanyalcin/meta-edgex) layer?
Or can we integrate it using any other methods?

**Comment by lenny-intel** [comment]
@Rohini8 , this question is very old. Can we close?

**Comment by iain-anderson** [comment]
closing as inactive

**Comment by lenny-intel** [comment]
@Devendra-7 , please do not post questions on old close issues. We now use Github discussions for these types of question. Please post your question(s) here: https://github.com/orgs/edgexfoundry/discussions 

Also, Fuji 1.1 is a very old release and has not been support for many years. We have just released Napa 3.1. Please use the latest release. Documentation is here: https://docs.edgexfoundry.org/3.1. Start with the getting started guides.
