### ISSUE TITLE
How to configure mqtt through edgex(version : Fuji) using meta-edgex layer

### ISSUE THREAD

**Issue by shalini-stack** [edgexfoundry/device-mqtt-go#331]
we have integrated meta-edgex layer of Fuji version in Yocto build (Gatesgarth) for imx8 board. We made changes to database parameter (from mongodb to redis) in configuration.toml of listed microservices of Edgex recipe:
1. core-metadata
2. export-distro
3. support-scheduler
4. core-data 
5. export-client
6. support-notifications
7. core-command 
8. support-logging	

Changes made in edgex-fuji-launch.sh :
commented support-logging	microservice in the above mentioned script file.

Procedure:
1. Made all the above changes
2. Ran edgex-fuji-launch.sh in background
3. Ran device-mqtt-launch.sh in background
4. Ran device-virtual-launch.sh 

The services are up but we are not able to see the messages (from MQTT test device) in HiveMQ mqtt client.

For all the microservices the events are as follows:
1. "Putting event on message queue"
2. "Event Published on message queue
3. Pushed event to core data"

Please let us know how to configure mqtt service (configuration.toml file) to publish the message to MQTT broker and to check the messages using HiveMQ client for Fuji version of EdgeX.

Is there any changes required to be done to export-client and export-distro (configuration.toml file)

Hereby attaching the logs on imx8 board:
[EdgeX-fuji-mqtt-logs-imx8.txt](https://github.com/edgexfoundry/device-mqtt-go/files/7683947/EdgeX-fuji-mqtt-logs-imx8.txt)

**Comment by shalini-stack** [comment]
File related to above issue is attached here

**Comment by shalini-stack** [comment]
file:///home/administrator/Projects/EdgeX-fuji-mqtt-logs-imx8

**Comment by lenny-intel** [comment]
@shalini-stack , Fuji is no longer supported please upgrade to latest Kamakura (2.2.0) release.
also see this example: https://docs.edgexfoundry.org/2.2/examples/Ch-ExamplesAddingMQTTDevice/#enabling-multi-level-topics

**Comment by iain-anderson** [comment]
closing as inactive
