### ISSUE TITLE
A confusion about the MQTT Device Service

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/device-mqtt-go#339]
hi , i followed the [documentation](https://docs.edgexfoundry.org/2.0/examples/Ch-ExamplesAddingMQTTDevice/) to learn how to use MQTT's device service.
I created the device my-custom-device step by step according to the document ,but the device failed to receive the GET and PUT methods.
![image](https://user-images.githubusercontent.com/25740210/154031550-f0e97bd4-695e-4c03-b227-2128d782444d.png)
![image](https://user-images.githubusercontent.com/25740210/154031624-fbcc31a5-aef6-4eaf-acdd-26d5b9afcc62.png)

These are the logs.
`level=ERROR ts=2022-02-15T08:58:51.896941054Z app=device-mqtt source=restrouter.go:158 X-Correlation-ID=46365588-8be2-403a-82f1-0ca49991eb63 msg="error reading DeviceResourece message for my-custom-device -> 'mqtt' protocol properties is not defined"`
Please tell me what the problem is. thank you！

**Comment by cloudxxx8** [comment]
how did you create the device? could you please paste the response of the core-metadata API call?
http://{hostname}:59881/api/v2/device/name/my-custom-device

**Comment by weichou1229** [comment]
What is the device-mqtt error logs when you run `curl http://localhost:59882/api/v2/device/name/MQTT-test-device/testmessage \ -H "Content-Type:application/json" -X PUT \ -d '{"message":"Hello!"}'`?

**Comment by FengZeHe** [comment]
> 

Thank you for your reply, please forgive me for being new.
I expect the response to look like a [document](https://docs.edgexfoundry.org/2.0/examples/Ch-ExamplesAddingMQTTDevice/#execute-set-command). How do I do that? Thank you very much!

**Comment by cloudxxx8** [comment]
@FengZeHe did you execute the "Run an MQTT Device Simulator" section to start `mock-device.js` with the correct broker IP address?

**Comment by FengZeHe** [comment]
> 



> @FengZeHe did you execute the "Run an MQTT Device Simulator" section to start `mock-device.js` with the correct broker IP address?

It is. It's my fault. Thanks for your reply！
