### ISSUE TITLE
What will be the path to mqtt-scripts 

### ISSUE THREAD

**Issue by tapeshmathur** [edgexfoundry/device-mqtt-go#384]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels such as Slack (edgexfoundry.slack.com)

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by cloudxxx8** [comment]
mqtt-scripts is not part of this repository
