### ISSUE TITLE
How to receive another data frame.

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-mqtt-go#388]
Hi all , I can receive the data form mqtt device service, but now I need to receive another data format.
The data frame as shown below:
+(0)---------+(1)------+(2)--------+(3)------------+(7)----------+(8)---------+(11)
|Device type |DAC type |Channel id |Reference time |Alarm status |Data sample |
|(1 byte)    |(1 byte) |(1byte)    |(4 bytes)      |(1 byte)     |(3 bytes)   |
+------------+---------+-----------+---------------+-------------+------------+

Are there any ways to solve this issue?

**Comment by cloudxxx8** [comment]
you can fork this reference implementation and customize it for your data format

**Comment by bighb69738** [comment]
Thank you ! @cloudxxx8
