### ISSUE TITLE
How to recognize the command from which devices.

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-mqtt-go#393]
Hi all,
I tried to receive the command from ComandTopic.
But I have a question, If I have two devices and need to control one of the devices by command.
How to recognize the command from which devices.
In my test, the comand request only can be read "cmd" "method" "uuid".
Ex: {"cmd":"message","message":"test123","method":"set","uuid":"62b40f52b8dd79000134ed9a"}
So, It seems cannot be supported me to recognize the command from which devices.

**Comment by cloudxxx8** [comment]
please try to use multiple level command topics
https://docs.edgexfoundry.org/2.2/examples/Ch-ExamplesAddingMQTTDevice/#enabling-multi-level-topics

**Comment by lenny-intel** [comment]
@bighb69738 , has you question be answered?
