### ISSUE TITLE
Testping command returns EOF

### ISSUE THREAD

**Issue by sagark82** [edgexfoundry/device-mqtt-go#398]
Hi, I am trying to create a device using the tutorial and docs on edgexfoundry pages. I am facing 2 issues: -
1. Not able to run commands
2. On sending data (image data in bytearray form via a python script) listener fails to read data
I am running everything on my local machine.

**Log**
level=INFO ts=2022-07-02T12:47:45.8064788Z app=edgex-device-mqtt source=config.go:219 msg="Loaded configuration from /custom-config/configuration.toml"
level=INFO ts=2022-07-02T12:47:45.8085867Z app=edgex-device-mqtt source=config.go:112 msg="Config Provider URL created from Registry configuration"
level=INFO ts=2022-07-02T12:47:45.8086549Z app=edgex-device-mqtt source=config.go:167 msg="Using Configuration provider (consul) from: http://edgex-core-consul:8500 with base path of edgex/devices/1.0/edgex-device-mqtt"
level=INFO ts=2022-07-02T12:47:50.108845Z app=edgex-device-mqtt source=config.go:330 msg="Configuration has been pushed to into Configuration Provider (0 environment overrides applied)"
level=INFO ts=2022-07-02T12:47:50.1093871Z app=edgex-device-mqtt source=registry.go:79 msg="Using Registry (consul) from http://edgex-core-consul:8500"
level=INFO ts=2022-07-02T12:47:50.1983996Z app=edgex-device-mqtt source=httpserver.go:94 msg="Web server starting (0.0.0.0:49982)"
level=INFO ts=2022-07-02T12:47:50.2198781Z app=edgex-device-mqtt source=init.go:134 msg="Check Metadata service's status via Registry..."
level=INFO ts=2022-07-02T12:47:50.2201013Z app=edgex-device-mqtt source=init.go:134 msg="Check Data service's status via Registry..."
level=INFO ts=2022-07-02T12:47:50.2446037Z app=edgex-device-mqtt source=init.go:42 msg="Service clients initialize successful."
level=DEBUG ts=2022-07-02T12:47:50.2603481Z app=edgex-device-mqtt source=service.go:76 msg="Trying to find Device Service: edgex-device-mqtt"
level=INFO ts=2022-07-02T12:47:50.3160406Z app=edgex-device-mqtt source=service.go:83 msg="Device Service edgex-device-mqtt doesn't exist, creating a new one"
level=INFO ts=2022-07-02T12:47:50.3280389Z app=edgex-device-mqtt source=service.go:140 msg="Addressable edgex-device-mqtt doesn't exist, creating a new one"
level=DEBUG ts=2022-07-02T12:47:50.3440728Z app=edgex-device-mqtt source=service.go:129 msg="New device service Id: bcd7e324-1552-4715-b0ba-2be76cfd333f"
level=DEBUG ts=2022-07-02T12:47:50.3528657Z app=edgex-device-mqtt source=service.go:93 msg="Device Service in Core MetaData: edgex-device-mqtt"
level=DEBUG ts=2022-07-02T12:47:50.3770682Z app=edgex-device-mqtt source=profiles.go:40 msg="created absolute path for loading pre-defined Device Profiles: /custom-config"
level=INFO ts=2022-07-02T12:47:50.3775582Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://:@192.168.1.4:1883 clientID=CommandResponseSubscriber "
level=INFO ts=2022-07-02T12:47:50.3775583Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://:@192.168.1.4:1883 clientID=IncomingDataSubscriber "
level=DEBUG ts=2022-07-02T12:47:50.4021349Z app=edgex-device-mqtt source=profiles.go:156 msg="Getting EnableValueDescriptorManagement configuration value from Core Metadata"
level=DEBUG ts=2022-07-02T12:47:50.4218548Z app=edgex-device-mqtt source=profiles.go:209 msg="ps: createDescriptor: ping, value: {\"type\":\"String\",\"readWrite\":\"R\",\"defaultValue\":\"pong\",\"size\":\"0\"}, units: {\"type\":\"String\",\"readWrite\":\"R\"}"
level=DEBUG ts=2022-07-02T12:47:50.4328849Z app=edgex-device-mqtt source=profiles.go:235 msg="profiles: created Value Descriptor id: fdc3e575-ed49-427b-bed8-74b218733bd5"
level=INFO ts=2022-07-02T12:47:50.4348783Z app=edgex-device-mqtt source=responselistener.go:63 msg="[Response listener] Start command response listening. "
level=INFO ts=2022-07-02T12:47:50.4375511Z app=edgex-device-mqtt source=incominglistener.go:65 msg="[Incoming listener] Start incoming data listening. "
level=DEBUG ts=2022-07-02T12:47:50.4418636Z app=edgex-device-mqtt source=profiles.go:209 msg="ps: createDescriptor: message, value: {\"type\":\"String\",\"readWrite\":\"W\",\"size\":\"0\"}, units: {\"type\":\"String\",\"readWrite\":\"R\"}"
level=DEBUG ts=2022-07-02T12:47:50.4693543Z app=edgex-device-mqtt source=profiles.go:235 msg="profiles: created Value Descriptor id: 0637ddef-0471-4a4e-84b6-92a5a6c00727"
level=DEBUG ts=2022-07-02T12:47:50.4772066Z app=edgex-device-mqtt source=profiles.go:209 msg="ps: createDescriptor: image, value: {\"type\":\"Binary\",\"readWrite\":\"R\"}, units: {\"type\":\"Binary\",\"readWrite\":\"R\"}"
level=DEBUG ts=2022-07-02T12:47:50.4852974Z app=edgex-device-mqtt source=profiles.go:235 msg="profiles: created Value Descriptor id: f32b5cd9-42a8-416b-b345-1ee729916479"
level=DEBUG ts=2022-07-02T12:47:50.4915257Z app=edgex-device-mqtt source=profiles.go:209 msg="ps: createDescriptor: randnum, value: {\"type\":\"Float64\",\"readWrite\":\"R\",\"size\":\"4\",\"floatEncoding\":\"eNotation\"}, units: {\"type\":\"String\",\"readWrite\":\"R\"}"
level=DEBUG ts=2022-07-02T12:47:50.5004183Z app=edgex-device-mqtt source=profiles.go:235 msg="profiles: created Value Descriptor id: caa71c3d-25f8-4299-93fb-44b8a6162782"
level=DEBUG ts=2022-07-02T12:47:50.5149774Z app=edgex-device-mqtt source=devices.go:22 msg="Loading pre-define Devices from configuration"
level=DEBUG ts=2022-07-02T12:47:50.52157Z app=edgex-device-mqtt source=devices.go:28 msg="Device MQ_DEVICE doesn't exist, creating a new one"
level=DEBUG ts=2022-07-02T12:47:50.5318847Z app=edgex-device-mqtt source=devices.go:60 msg="Adding Device: {\"origin\":1656766070531,\"description\":\"General MQTT device\",\"name\":\"MQ_DEVICE\",\"adminState\":\"UNLOCKED\",\"operatingState\":\"ENABLED\",\"protocols\":{\"mqtt\":{\"ClientId\":\"CommandPublisher\",\"CommandTopic\":\"CommandTopic\",\"Host\":\"192.168.1.4\",\"Password\":\"\",\"Port\":\"1883\",\"Schema\":\"tcp\",\"Topic\":\"CommandTopic\",\"User\":\"\"}},\"labels\":[\"MQTT\"],\"service\":{\"origin\":1656766070336,\"id\":\"bcd7e324-1552-4715-b0ba-2be76cfd333f\",\"name\":\"edgex-device-mqtt\",\"operatingState\":\"ENABLED\",\"addressable\":{\"origin\":1656766070334,\"id\":\"1550e194-6792-4239-b5ab-f37c11551a85\",\"name\":\"edgex-device-mqtt\",\"protocol\":\"HTTP\",\"method\":\"POST\",\"address\":\"edgex-device-mqtt\",\"port\":49982,\"path\":\"/api/v1/callback\",\"baseURL\":\"http://edgex-device-mqtt:49982\",\"url\":\"http://edgex-device-mqtt:49982/api/v1/callback\"},\"adminState\":\"UNLOCKED\"},\"profile\":{\"description\":\"Test device profile\",\"id\":\"b87bb91e-5599-41fd-bab9-08b6516e1b43\",\"name\":\"Test.Device.MQTT.Profile\",\"manufacturer\":\"iot\",\"model\":\"MQTT-DEVICE\",\"labels\":[\"mqtt\",\"test\"],\"deviceResources\":[{\"description\":\"device image\",\"name\":\"image\",\"properties\":{\"value\":{\"type\":\"Binary\",\"readWrite\":\"R\"},\"units\":{\"type\":\"Binary\",\"readWrite\":\"R\"}}},{\"description\":\"device random number\",\"name\":\"randnum\",\"properties\":{\"value\":{\"type\":\"Float64\",\"readWrite\":\"R\",\"size\":\"4\",\"floatEncoding\":\"eNotation\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}},{\"description\":\"device awake\",\"name\":\"ping\",\"properties\":{\"value\":{\"type\":\"String\",\"readWrite\":\"R\",\"defaultValue\":\"pong\",\"size\":\"0\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}},{\"description\":\"device message\",\"name\":\"message\",\"properties\":{\"value\":{\"type\":\"String\",\"readWrite\":\"W\",\"size\":\"0\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}],\"deviceCommands\":[{\"name\":\"testping\",\"get\":[{\"index\":\"1\",\"operation\":\"get\",\"object\":\"ping\",\"deviceResource\":\"ping\",\"parameter\":\"ping\"}]},{\"name\":\"testmessage\",\"get\":[{\"index\":\"1\",\"operation\":\"get\",\"object\":\"message\",\"deviceResource\":\"message\",\"parameter\":\"message\"}],\"set\":[{\"index\":\"1\",\"operation\":\"set\",\"object\":\"message\",\"deviceResource\":\"message\",\"parameter\":\"message\"}]},{\"name\":\"testimage\",\"get\":[{\"index\":\"1\",\"operation\":\"get\",\"object\":\"image\",\"deviceResource\":\"image\",\"parameter\":\"image\"}]},{\"name\":\"testrandnum\",\"get\":[{\"index\":\"1\",\"operation\":\"get\",\"object\":\"randnum\",\"deviceResource\":\"randnum\",\"parameter\":\"randnum\"}]}],\"coreCommands\":[{\"name\":\"testimage\",\"get\":{\"path\":\"/api/v1/device/{deviceId}/testimage\",\"responses\":[{\"code\":\"200\",\"description\":\"get the image value\",\"expectedValues\":[\"image\"]},{\"code\":\"503\",\"description\":\"service unavailable\"}]}},{\"name\":\"testrandnum\",\"get\":{\"path\":\"/api/v1/device/{deviceId}/testrandnum\",\"responses\":[{\"code\":\"200\",\"description\":\"get the random value\",\"expectedValues\":[\"randnum\"]},{\"code\":\"503\",\"description\":\"service unavailable\"}]}},{\"name\":\"testping\",\"get\":{\"path\":\"/api/v1/device/{deviceId}/testping\",\"responses\":[{\"code\":\"200\",\"description\":\"ping the device\",\"expectedValues\":[\"ping\"]},{\"code\":\"503\",\"description\":\"service unavailable\"}]}},{\"name\":\"testmessage\",\"get\":{\"path\":\"/api/v1/device/{deviceId}/testmessage\",\"responses\":[{\"code\":\"200\",\"description\":\"get the message\",\"expectedValues\":[\"message\"]},{\"code\":\"503\",\"description\":\"service unavailable\"}]},\"put\":{\"path\":\"/api/v1/device/{deviceId}/testmessage\",\"responses\":[{\"code\":\"204\",\"description\":\"set the message.\"},{\"code\":\"503\",\"description\":\"service unavailable\"}],\"parameterNames\":[\"message\"]}}]},\"autoEvents\":[{}]}"
level=INFO ts=2022-07-02T12:47:50.5447709Z app=edgex-device-mqtt source=message.go:50 msg="Service dependencies resolved..."
level=INFO ts=2022-07-02T12:47:50.545055Z app=edgex-device-mqtt source=autodiscovery.go:19 msg="AutoDiscovery stopped: disabled by configuration"
level=INFO ts=2022-07-02T12:47:50.5536528Z app=edgex-device-mqtt source=message.go:51 msg="Starting edgex-device-mqtt 1.2.1 "
level=INFO ts=2022-07-02T12:47:50.5572651Z app=edgex-device-mqtt source=device.go:58 msg="Added device: MQ_DEVICE"
level=INFO ts=2022-07-02T12:47:50.5638107Z app=edgex-device-mqtt source=message.go:55 msg="device mqtt started"
level=DEBUG ts=2022-07-02T12:47:50.5988437Z app=edgex-device-mqtt source=driver.go:454 msg="Device MQ_DEVICE is added"
level=INFO ts=2022-07-02T12:47:50.6035553Z app=edgex-device-mqtt source=message.go:58 msg="Service started in: 4.8099425s"
level=DEBUG ts=2022-07-02T12:47:50.6214893Z app=edgex-device-mqtt source=device.go:67 msg="Invoked driver.AddDevice callback for MQ_DEVICE"
level=DEBUG ts=2022-07-02T12:47:50.6338465Z app=edgex-device-mqtt source=device.go:74 msg="Handler - starting AutoEvents for device MQ_DEVICE"
level=ERROR ts=2022-07-02T12:47:50.6454766Z app=edgex-device-mqtt source=executor.go:134 msg="AutoEvent Frequency  cannot be parsed error, time: invalid duration "
level=ERROR ts=2022-07-02T12:47:50.6522418Z app=edgex-device-mqtt source=manager.go:67 msg="AutoEvent for resource  cannot be created, time: invalid duration "
level=WARN ts=2022-07-02T12:48:51.3513042Z app=edgex-device-mqtt source=incominglistener.go:120 msg="[Incoming listener] Incoming reading ignored. No name found : msg=map[]"
level=DEBUG ts=2022-07-02T12:56:26.7295573Z app=edgex-device-mqtt source=command.go:221 msg="Handler - execReadCmd: deviceResource: image"
level=DEBUG ts=2022-07-02T12:56:26.734999Z app=edgex-device-mqtt source=command.go:228 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device image\",\"name\":\"image\",\"properties\":{\"value\":{\"type\":\"Binary\",\"readWrite\":\"R\"},\"units\":{\"type\":\"Binary\",\"readWrite\":\"R\"}}}"
level=INFO ts=2022-07-02T12:56:26.7411697Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://:@192.168.1.4:1883 clientID=CommandPublisher "
level=INFO ts=2022-07-02T12:56:26.7691365Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"image\",\"method\":\"get\",\"uuid\":\"62c0407ab8dd790001ee79f1\"}"
level=INFO ts=2022-07-02T12:56:31.7804477Z app=edgex-device-mqtt source=driver.go:125 msg="Handle read commands failed: can not fetch command response: method=get cmd=image"
level=DEBUG ts=2022-07-02T12:56:31.9336459Z app=edgex-device-mqtt source=utils.go:293 msg="Update of last connected times is disabled for: MQ_DEVICE"
**level=WARN ts=2022-07-02T13:01:08.4943795Z app=edgex-device-mqtt source=incominglistener.go:120 msg="[Incoming listener] Incoming reading ignored. No name found : msg=map[]"
level=DEBUG ts=2022-07-02T13:14:13.8226416Z app=edgex-device-mqtt source=command.go:221 msg="Handler - execReadCmd: deviceResource: ping"
level=DEBUG ts=2022-07-02T13:14:13.9268224Z app=edgex-device-mqtt source=command.go:228 msg="Handler - execReadCmd: deviceResource: {\"description\":\"device awake\",\"name\":\"ping\",\"properties\":{\"value\":{\"type\":\"String\",\"readWrite\":\"R\",\"defaultValue\":\"pong\",\"size\":\"0\"},\"units\":{\"type\":\"String\",\"readWrite\":\"R\"}}}"
level=INFO ts=2022-07-02T13:14:13.9467885Z app=edgex-device-mqtt source=driver.go:282 msg="Create MQTT client and connection: uri=tcp://:@192.168.1.4:1883 clientID=CommandPublisher "
level=INFO ts=2022-07-02T13:14:13.9909261Z app=edgex-device-mqtt source=driver.go:157 msg="Publish command: {\"cmd\":\"ping\",\"method\":\"get\",\"uuid\":\"62c044a5b8dd790001ee79f2\"}"
level=INFO ts=2022-07-02T13:14:19.0092058Z app=edgex-device-mqtt source=driver.go:125 msg="Handle read commands failed: can not fetch command response: method=get cmd=ping"
level=DEBUG ts=2022-07-02T13:14:19.7091534Z app=edgex-device-mqtt source=utils.go:293 msg="Update of last connected times is disabled for: MQ_DEVICE"**
[profile.zip](https://github.com/edgexfoundry/device-mqtt-go/files/9033057/profile.zip)

**Comment by sagark82** [comment]
issue#2 is solved, I had to send the data in json (key value pair) format. On doing that, event is sent to core data.

However issue 1 is still present

**Comment by cloudxxx8** [comment]
please describe your steps
