### ISSUE TITLE
ERROR: libcurl-7.80.0-r1: package mentioned in index not found.

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-mqtt-go#400]
Error occurred when making docker.

<img width="962" alt="截圖 2022-07-04 下午3 30 19" src="https://user-images.githubusercontent.com/38970513/177105001-54d0c909-a61b-4791-bf67-c4c3076c1699.png">

**Comment by cloudxxx8** [comment]
please try to verify whether this change can work
https://github.com/edgexfoundry/edgex-go/pull/4069/files

**Comment by bighb69738** [comment]
@cloudxxx8 
Yes, it can work!
Thank you!
