### ISSUE TITLE
why started http2write command with mutil threads ， but for many devices ，all of concur size of http is only 4? 

### ISSUE THREAD

**Issue by BermudaGhol** [edgexfoundry/device-mqtt-go#405]
why started http2write command for mutil threads ， but for many devices ，all of concurrent- size of http is only 4? 

_----------start try to send http------_
vel=INFO ts=2022-07-21T07:02:14.037223Z app=device-mqtt source=driver.go:236 msg="write start --- "
level=INFO ts=2022-07-21T07:02:14.038183Z app=device-mqtt source=driver.go:236 msg="write start --- "
level=INFO ts=2022-07-21T07:02:14.039109Z app=device-mqtt source=driver.go:236 msg="write start --- "
level=INFO ts=2022-07-21T07:02:14.040259Z app=device-mqtt source=driver.go:236 msg="write start --- "
_--(suspect for 6 request but 4 and await )---_
2022/07/21 15:02:14 time return %!(EXTRA time.Time=0001-01-01 00:00:00 +0000 UTC)
level=ERROR ts=2022-07-21T07:02:17.53333Z app=device-mqtt source=restrouter.go:167 X-Correlation-ID= msg="error writing DeviceResourece message for 1 -> 超时未获取到状态，走推送"
level=ERROR ts=2022-07-21T07:02:17.533365Z app=device-mqtt source=restrouter.go:167 X-Correlation-ID= msg="error writing DeviceResourece message for 2 -> 超时未获取到状态，走推送"
level=ERROR ts=2022-07-21T07:02:17.533422Z app=device-mqtt source=restrouter.go:167 X-Correlation-ID= msg="error writing DeviceResourece message for 1 -> 超时未获取到状态，走推送"
level=ERROR ts=2022-07-21T07:02:17.533493Z app=device-mqtt source=restrouter.go:167 X-Correlation-ID= msg="error writing DeviceResourece message for 1 -> 超时未获取到状态，走推送"
_**--》 4 response  over
--〉start another 2**_ 

level=INFO ts=2022-07-21T07:02:17.563997Z app=device-mqtt source=driver.go:236 msg="write start --- "
2022/07/21 15:02:17 time return %!(EXTRA time.Time=0001-01-01 00:00:00 +0000 UTC)
level=INFO ts=2022-07-21T07:02:17.566173Z app=device-mqtt source=driver.go:236 msg="write start --- "
2022/07/21 15:02:17 time return %!(EXTRA time.Time=0001-01-01 00:00:00 +0000 UTC)

level=ERROR ts=2022-07-21T07:02:21.028848Z app=device-mqtt source=restrouter.go:167 X-Correlation-ID= msg="error writing DeviceResourece message for 2 -> 超时未获取到状态，走推送"
level=ERROR ts=2022-07-21T07:02:21.028952Z app=device-mqtt source=restrouter.go:167 X-Correlation-ID= msg="error writing DeviceResourece message for 2 -> 超时未获取到状态，走推送"

**_my sender's url :> http://localhost:59982/api/v2/device/name/"+ i +"/message?req=1" body is : {"messages":"djadiadajdoadjao"}_**

**Am I need some other config propertys in configuration.toml ?** 
Thank you!

**Comment by cloudxxx8** [comment]
this is not a device-sdk-go issue, so move to device-mqtt-go repository

**Comment by BermudaGhol** [comment]
its same，

**Comment by cloudxxx8** [comment]
I really don't understand your question in this issue

**Comment by cloudxxx8** [comment]
I see.
We don't set the limit in the service.  This should be the http client limit in CLI.
https://stackoverflow.com/questions/47385692/limited-concurrent-connections-in-go
You can see the DefaultMaxIdleConnsPerHost in the godoc
https://pkg.go.dev/net/http

You can write your own http client for more test
https://xujiahua.github.io/posts/20200723-golang-http-reuse/

**Comment by iain-anderson** [comment]
closing as inactive - please re-open if required
