### ISSUE TITLE
How to run built image via docker run, and via docker-compose file

### ISSUE THREAD

**Issue by tntthanh** [edgexfoundry/device-mqtt-go#409]
Hi everyone, I had built this service to executable file and run it working perfectly, but when I build docker image and then run, it always returns error "...msg="Retryable failure while creating SecretClient: open /tmp/edgex/secrets/device-mqtt/secrets-token.json: no such file or directory"...". Please help me with this...

By the way, I had push my image to docker hub. I wonder how can I use it in docker-compose.yml file from edgex-compose along with other edgex-compose services (e.g: edgex-core-data, edgex-core-metadata,...)

Thank you very much!

**Comment by cloudxxx8** [comment]
by default the service treats the security is enabled, so it tries to create a secret client with the default token path.
if you are running the service in binary or IDE, you can define environment variable `EDGEX_SECURITY_SECRET_STORE: "false"` in the IDE or terminal.  

you need to build the image via Dockerfile, not docker-compose file.
you can modify the image url in the docker-compose file to your docker repository URL.

**Comment by tntthanh** [comment]
Hi @cloudxxx8, exactly, I actually want to use secty version, is there a solution for this

**Comment by cloudxxx8** [comment]
you need to add your service to the secretstore-setup settings.  the simplest way is to add an environment variable to the secretstore-setup in the docker-compose file:
`ADD_SECRETSTORE_TOKENS: 'device-mqtt'`

Then, it will generate the secret store token under ` /tmp/edgex/secrets/device-mqtt/secrets-token.json`
Please see the document:
https://docs.edgexfoundry.org/2.2/security/Ch-Configuring-Add-On-Services/

If your service is running in docker, you need to add the volume mapping to access this folder, too.
for example:
```
    volumes:
    - /tmp/edgex/secrets/device-mqtt:/tmp/edgex/secrets/device-mqtt:ro,z
```

**Comment by tntthanh** [comment]
Thank you very much @cloudxxx8. Similarly, I had added the flag -v and flag --network when execute "docker run":
docker run -v /tmp/edgex/secrets/device-mqtt:/tmp/edgex/secrets/device-mqtt:ro,z --network="host" {{docker_image_id}}
, and the error was solved. However, it still remained the following error, please help me:
"...
level=ERROR ts=2022-08-09T03:41:14.07154563Z app=device-mqtt source=bootstrap.go:46 msg="failed to create Configuration Provider client: failed to get Configuration Provider (consul) access token: HTTP response with status code 400, message: failed to generate Consul token using [device-mqtt]: {\"errors\":[\"role \\\"device-mqtt\\\" not found\"]}\n"
..."

**Comment by tntthanh** [comment]
Also, I got this error when I use the docker image within my docker-compose file (I build and push device-mqtt to my docker hub repo, and then pull it to use while running the docker-compose file). Log of the error is following:
"...
edgex-device-mqtt        | level=INFO ts=2022-08-09T04:15:31.93049253Z app=security-bootstrapper source=config.go:391 msg="Loaded service configuration from /edgex-init/res/configuration.toml"
edgex-device-mqtt        | invalid value "" for flag -timeout: parse error
edgex-device-mqtt        | Usage of waitFor:
edgex-device-mqtt        |   -confdir string
edgex-device-mqtt        |     	
edgex-device-mqtt        |   -retryInterval duration
edgex-device-mqtt        |     	Duration to pause before retrying (default 1s)
edgex-device-mqtt        |   -timeout duration
edgex-device-mqtt        |     	Timeout duration of waiting for services (default 10s)
edgex-device-mqtt        |   -uri value
edgex-device-mqtt        |     	Service (tcp/tcp4/tcp6/http/https/unix/file) to wait for before this one starts. Can be passed multiple times. e.g. tcp://db:5432
edgex-device-mqtt        | level=INFO ts=2022-08-09T04:15:31.93491777Z app=security-bootstrapper source=config.go:551 msg="Using local configuration from file (0 envVars overrides applied)"
edgex-device-mqtt        | level=ERROR ts=2022-08-09T04:15:31.935373902Z app=security-bootstrapper source=init.go:76 msg="Unable to parse command: -uri tcp://: -timeout : invalid value \"\" for flag -timeout: parse error"
..."

**Comment by tntthanh** [comment]
Hi everyone, I had solve the problem by adding essential environment variables to the docker-compose file. Thank you very much, I close this
