### ISSUE TITLE
编译2.3.0发行版本时，报错，无法完成编译

### ISSUE THREAD

**Issue by lyh0302** [edgexfoundry/device-mqtt-go#501]
# 🐞 Bug Report

# github.com/pebbe/zmq4
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/reactor.go:10:4: undefined: State
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/reactor.go:11:9: undefined: State
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/reactor.go:21:16: undefined: Socket
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/reactor.go:23:12: undefined: Poller
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/reactor.go:61:34: undefined: Socket
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/reactor.go:61:49: undefined: State
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/reactor.go:68:37: undefined: Socket
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/utils.go:17:12: undefined: Socket
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/utils.go:24:12: undefined: Socket
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/utils.go:28:12: undefined: Socket
/home/liyuhui/golang/gopath/pkg/mod/github.com/pebbe/zmq4@v1.2.7/utils.go:28:12: too many errors

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu16.04 
**EdgeX Version [**REQUIRED**]:**
device-mqtt-go.2.3.0
**Anything else relevant?**

**Comment by cloudxxx8** [comment]
your build environment have to install zero mq for the compilation.
https://zeromq.org/download/

by the way, we removed zero mq in v3.0

**Comment by lenny-intel** [comment]
Closing as answered
