### ISSUE TITLE
Make multi-level topics the only implementation

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-mqtt-go#551]
# 🚀 Tech Debt

### Relevant Package [**REQUIRED**]

 This feature request is for handling data from external MQTT

### Description [**REQUIRED**]
 Currently to original JSON wrapper is use as the payload sent via MQTT is  the default and the new approach of multi-level topics is optional and must be enabled.

### Describe the solution you'd like
 Make multi-level topics the only option. Remove the JSON wrapper implementation

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds? Make multi-level topics the default, but leave JSON wrapper implementation as an option. This doesn't clean-up the code and we still have both approaches to maintain.

**Comment by lenny-intel** [comment]
@cloudxxx8 , @iain-anderson , thoughts on removing the old JSON wrapper implementation in favor of the new multi-level topics implementation?

**Comment by cloudxxx8** [comment]
I am fine with this change

**Comment by iain-anderson** [comment]
OK with me
