### ISSUE TITLE
Edgex mqtt error

### ISSUE THREAD

**Issue by nbenhur** [edgexfoundry/device-mqtt-go#666]
I am using edgex and communicating with espc6 microcontroller using mqtt protocol. Edgex V2.3 is running on docker environment. Ubuntu 22.04 OS environment is used. Followed https://docs.edgexfoundry.org/2.3/examples/Ch-ExamplesAddingMQTTDevice/ link. From the link i am testing "Execute SET Command" using curl command from bash shell. I am getting success status 200 for up-to 9 tabs or windows. From 10th tab on wards  i fails with error code 500. I tested the same on two machines with different configurations like intel i3 processor with 8Gb ram and another i7 processor with 16Gb ram. I am getting same results i.e. up-to 9 tabs getting success 200 code. I need help on how to increase more number of tabs or connections to edgex mqtt device. As i have more microcontrollers connecting to edgex using mqtt. Please guide.
![Screenshot from 2024-03-13 16-56-55](https://github.com/edgexfoundry/device-mqtt-go/assets/22791386/1698e871-83ab-474f-8f4e-c568eb03323a)

**Comment by jiekechoo** [comment]
Currently, the EdgeX v3.1(Napa) is the LTS version. Could you please use the latest release version of EdgeX?

**Comment by nbenhur** [comment]
First we tried with v3.1(Napa), there also we faced same problem. So, we tested with V2.3. Here also getting same problem.

**Comment by jiekechoo** [comment]
Could you provide the configuration.yaml file, profile.yaml and device.yaml?

Some error log with text is preferred.

**Comment by jiekechoo** [comment]
It seems not an EdgeX issue. Did you test the MQTT connection with the esp32 device using your script?

And, you should use the latest version of EdgeX that the community can support you as well.

**Comment by nbenhur** [comment]
On the bash shell, curl command is given to set the message in edgex. I am sending curl command using shell script which will send command for every 45 secs in a loop. I tested this on 10 tabs simultaneously. Until 9 tabs i am getting success status code 200. 
For the first tab, the response is getting within 2 secs. As the tabs increases the response getting time interval is increasing. At the 9th tab the response time interval is nearly 4 to 5 sec. At the 10th tab the response time interval is more than 5 secs. 

Initially only error 500 is coming when there is no response from edgex.  Later i changed some settings in consol 1.ResponseFetchInterval value changed from 500ms to 1000ms. 2.Corecommand service request timeout from 45s to 60secs. 3.KeepAlive to 3600. From then on-wards i am getting "err: HTTP request timeout","statusCode":503", error. 

I want to know where is the option in the edgex to increase the http request timeout.

**Comment by jiekechoo** [comment]
It's not a timeout setting issue. The status code 503 means your devices didn't return anything.
Try to connect the esp devices using curl directly .

**Comment by nbenhur** [comment]
I tested connection with esp device using curl directly. I tested it with 10 tabs simultaneously. There is no loss in data from all the tabs. The curl command i used is "i=100; while :; i=$((i+1)); do curl -d $i mqtt://localhost/command/espc7/newmessage/set/293d7a00-66e1-4374-ace0-07520103c95f; sleep 45; done". Attached screenshot
![Screenshot from 2024-03-20 23-17-50](https://github.com/edgexfoundry/device-mqtt-go/assets/22791386/4ad03cf9-fed3-4c70-8158-fcc9eebc60de)
.

**Comment by jiekechoo** [comment]
I'll test the case in a few days.

**Comment by nbenhur** [comment]
I tested the same with raspberry pi pico board and edgex. I did concurrent tabs upto 20, sending curl requests to edgex on mqtt. There is no loss in the connection. I think there is problem with the mqtt on esp32. Thanks for your support.

**Comment by jiekechoo** [comment]
@nbenhur Please close the issue, thanks.
