### ISSUE TITLE
Command endpoints can return status=500; which doesn't exist in the device profile, nor is indicated by Core Metadata

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-mqtt-go#90]
When unexpected errors occurs, this device service will return the HTTP status code 500.

This isn't indicated in the default device profile for this device service, nor does it automatically get included in the list of possible return values returned by Core Metadata from the device endpoint:

> $ curl -s http://localhost:48081/api/v1/device/name/MQTT%20test%20device

This can be reproduced by starting this device service without a corresponding MQTT peer application, and then issuing a command either directly to the device service or via Core Command:

> $ curl -w "%{http_code}" http://localhost:49982/api/v1/device/21a5e108-ef33-4d48-b931-81afa739f092/testrandfloat32
> Handler - execReadCmd: error for Device: MQTT test device cmd: testrandfloat32, can not fetch command response: method=get cmd=randfloat32 /api/v1/device/21a5e108-ef33-4d48-b931-81afa739f092/testrandfloat32
> 500

I reproduced this with the following snaps:

Here are the versions of the snaps I'm using:

edgex-device-mqtt 1.0.0-20190801+fd7235a
edgexfoundry 1.0.1-20190729+c28b77d1

**Comment by weichou1229** [comment]
Do you mean device profile need to add 500 http status code in the coreCommands?
https://github.com/edgexfoundry/device-mqtt-go/blob/master/cmd/res/example/mqtt.test.device.profile.yml#L59

**Comment by cloudxxx8** [comment]
@weichou1229 please replace 503 with 500 in example profile
currently, it only supports 400, 404, 423, and 500 in device-sdk-go

**Comment by cloudxxx8** [comment]
the description doesn't change to internal server error
